### ISSUE TITLE
OSX kext injection feature

### ISSUE THREAD

**Issue by liqili** [dakanji/RefindPlus#107]
### Suggested Feature

Is it possible to add the new features like PCIE properties injection and kext injection like OpenCore bootloader?

**Comment by dakanji** [comment]
It is possible, but there is no intention to add this to RefindPlus at this time ... unless it is added upstream of course, in which case it will be added here in turn.

You can always add a RefindPlus manual stanza to load OpenCore if you need this functionality.
This tool might also provide some of what you want: https://github.com/jslegendre/ACPIPatcher
