### ISSUE TITLE
AP DBG will not let Big Sur or Monterey boot

### ISSUE THREAD

**Issue by MarioG-X** [dakanji/RefindPlus#108]
### RefindPlus Version

v0.13.2.AP Release

### Device Type

Apple Mac

### Problem Description

AP DBG does not let any Big Sur or Monterey boot to completion, macOS shows apple and stops there, Catalina and Linux booted ok. AP REL is good. I discovered the while tested. Bummer, it was looking good until the last tests:

AP Results: All partitions on 2 Macs booted fine, all internal HD/SSD unless specified, used drivers:
From Refind 13.3.1: EXT4
From RP AP: BTRFS and ISO.

Mac mini 2014 - AP DBG
HD BTRFS OpenSUSE 1 good
SSD APFS Big Sur failed
SSD APFS Monterey failed, log below.

Mac mini 2014 - AP REL all good
HD BTRFS OpenSUSE 1
HD BTRFS OpenSUSE 2
HD EXT4 Elementary OS
HD APFS Monterey
SSD APFS Catalina
SSD APFS Big Sur
SSD APFS Monterey

iMac 2012 AP REL all good
HD BTRFS OpenSUSE 1
HD EXT4 Elementary OS
HD APFS Catalina
SSD BTRFS OpenSUSE 2
SSD APFS Catalina

### Problem Point

After starting a loader or tool

### Affected Items

MacOS Loader

### Debug Log

[22h20u2401.log](https://github.com/dakanji/RefindPlus/files/8524401/22h20u2401.log)

**Comment by MarioG-X** [comment]
I decided to test on the iMac 2012 using DBG and it booted Catalina fine. Here is the log:
[22h20v5922.log](https://github.com/dakanji/RefindPlus/files/8524944/22h20v5922.log)

**Comment by MarioG-X** [comment]
Since the 2012 booted DBG with Catalina, I test the Mini 2014 with Catalina and AP boots it fine:
[22h20w0358.log](https://github.com/dakanji/RefindPlus/files/8525025/22h20w0358.log)

So it appears its related to booting Big Sur and Monterey.

**Comment by MarioG-X** [comment]
And finally: I retested X229 DBG and it boots Monterey fine. So something changed between X229 and AP that broke Big Sur and Monterey booting from AP. X229 Log:
[22h20w1044.log](https://github.com/dakanji/RefindPlus/files/8525062/22h20w1044.log)

**Comment by dakanji** [comment]
I see ... Try adding `decline_nvramprotect` to your config and see if that affects the outcome

**Comment by MarioG-X** [comment]
That did it. So commenting it is OK for REL but not DBG. Should be the same I assume to comments it since it sounds like a good thing. Log:
[22h20w1950.log](https://github.com/dakanji/RefindPlus/files/8525135/22h20w1950.log)

**Comment by dakanji** [comment]
Use `decline_panicfilter` instead

**Comment by MarioG-X** [comment]
I commented decline_nvramprotect and uncommented decline_panicfilter and that allowed booting as well:
[22h20w4902.log](https://github.com/dakanji/RefindPlus/files/8525376/22h20w4902.log)

**Comment by dakanji** [comment]
The `PanicFilter` feature will be removed from the next release and implemented in OpenCore instead.
It is not needed by users booting Big Sur and Monterey via RefindPlus (Supported Macs).

**Comment by MarioG-X** [comment]
I tested the modified AP DBG and it now works fine with both lines commented. Thanks!
