### ISSUE TITLE
Mac OS Updates Fail to Complete

### ISSUE THREAD

**Issue by MarioG-X** [dakanji/RefindPlus#111]
### RefindPlus Version

v0.13.2.AP Release

### Device Type

Apple Mac

### Problem Description

AP (and X233) prevents macOS updates from completing. Testing all failed the same way:
iMac 27 2012 with 2 Catalina systems
Mac mini 2014 with 1 Big Sur and 2 Monterey systems

I installed RP AN to determine this issue is related to AP and not macOS or firmware. I also tested by renaming the refind folder to refindx (any rename would probably work) and the updates worked.

Here is what used to happen with RP AN and previous:
1. Update any macOS from the Settings, and it would download, install, and reboot a few times.
2. Final reboot would work and RP would be deactivated by the process
3. Reinstall Refind, then RP to get back to RP booting.

Here is what happens with AP and X233:
1. Update any macOS from the Settings, and it would download, install, and reboot a few times.
2. What should be the final reboot would display the RP menu, booting into anything does not finish the install

Any tests are very time consuming because each one requires to start the update all over again, so about an hour apiece (I had 5 systems to update). And to retest after a successful update requires restoring the older manOS.

If it's too much to figure out then documentation should be provided to let people know they must **deactivate RP AP+ before any maOS update**.

### Problem Point

Other

### Affected Items

MacOS Loader

### Debug Log

I attempted to get an AP log but was not successful.

**Comment by dakanji** [comment]
Thanks for the report but without log files, for each reboot to try to track what is happening, I'm afraid this cannot be looked into and will be tagged as Incomplete unfortunately.

The RefindPlus DBG file generates logs unconditionally and always does so immediately it starts. The only time RefindPlus will not generate a log is if a DBG file is not in use (the REL file is in use), or if there is no writeable ESP.

On this:
> If it's too much to figure out then documentation should be provided to let people know they must deactivate RP AP+ before any maOS update.

There isn't enough information to be definite about this conclusion at this stage.

Thanks again!

**Comment by MarioG-X** [comment]
I restore non-updated macOS.
This is log of 233 debug normal boot before requesting update:
[22j19t3417.log](https://github.com/dakanji/RefindPlus/files/8733194/22j19t3417.log)

This is log of 233 debug boot after the update booting into the final boot, I had to manually select the "update" volume in the menu, normally this does not display in RP:
[22j19u4202.log](https://github.com/dakanji/RefindPlus/files/8733594/22j19u4202.log)

Next try with decline_nvramprotect active.

**Comment by dakanji** [comment]
Sorry but X233 was only relevant for the specific test it was provided for.
I believe this was before the 0.13.2.AP release in any case so don't consider it a benchmark instance.

Since you have used it so far though, you might as well run the `decline_nvramprotect` test with it for consistency.
Only problem is that any results you get might not be a reflection of the actual code since it was modified before release.

Anyway, go ahead and let's see.

I need to find a way to make such test builds provided temporary ... maybe build in a time based kill switch to avoid such situations.

**Comment by dakanji** [comment]
I agree expiration will not likely not work out well.
Just proceed with X233 or if not started, switch to the 0.13.2.AP for the final test.

**Comment by MarioG-X** [comment]
The test with 233 and decline_nvramprotect finally finished successfully, been running since the last test finished! It did the update but seemed to reboot macOS (not a hardware boot) several times more than before, but that could be my imagination. It did remove RP from booting as normally expected, so I need to reset that. Here is the last log:
[22j19v1525.log](https://github.com/dakanji/RefindPlus/files/8734156/22j19v1525.log)

Since this is such a complex and long test I am not sure how often I can test this, if I do it again I need to restore the volume prior to the update. At least it looks like decline_nvramprotect did allow it to work. Back to 233 REL for now.

**Comment by dakanji** [comment]
Thanks. No need for further tests.

Will tag this as a bug and push a fix later.
