### ISSUE TITLE
Reduce the need to press "Enter" twice to run loaders

### ISSUE THREAD

**Issue by MarioG-X** [dakanji/RefindPlus#113]
### RefindPlus Version

v0.13.3.AA Release

### Device Type

Apple Mac

### Problem Description

On previous and 13AA if a bootable USB is connected ALL menu selections requires pressing Enter twice. This is a very minor issue/observation that I thought you may want to know about since it was reported by someone else.

This is a very minor issue first reported by starters: https://github.com/dakanji/RefindPlus/discussions/105#discussioncomment-2621815 (in his case not a USB) that I never experienced until recently booted from a USB thumb drive. In my case it only occurs when booting from a USB drive. The issue is complex because it varies by REL vs DBG.

**CORRECTED**: Here are the combinations and logs, you need to follow carefully since REL and DBG are different:

• This issue never happens on my two iMacs if a bootable USB thumb drive is NOT connected.
• This issue always happens on my two iMacs if a bootable USB thumb is connected.
• It does not happen booting macOS from an external HD
• If I move the cursor to any selection and press Enter, then move to another selection and Enter, it will boot the second selection.

Using REL:
• If I tab and press enter normally/quickly, nothing happens unless I press a second time to boot.
[RELNOWAIT.log](https://github.com/dakanji/RefindPlus/files/8853988/RELNOWAIT.log)
 • If I tab and WAIT 10 seconds, then press enter a second time it boots.
[RELWAIT10.log](https://github.com/dakanji/RefindPlus/files/8854007/RELWAIT10.log)

Using DBG:
• If I tab and press enter normally/quickly, nothing happens unless I press a second time to boot.
[DBGNOWAIT.log](https://github.com/dakanji/RefindPlus/files/8854048/DBGNOWAIT.log)
 • If I tab and WAIT 10 seconds, then press enter a second time it boots.
[DBGWAIT.log](https://github.com/dakanji/RefindPlus/files/8854051/DBGWAIT.log)

### Problem Point

Before starting a loader or tool

### Affected Items

Other Item

### Debug Log

See above

**Comment by dakanji** [comment]
The threshold is larger when an external drive is connected because the issue it targets is worse under those circumstances. The threshold is always there but just too short for you to notice on a Mac when an external drive is not present.

**Comment by MarioG-X** [comment]
Also, it has nothing to do with how quick you press, if I wait 10 seconds or 1 minute, I still have to press Enter twice.

**Comment by MarioG-X** [comment]
It's alway the case on both Macs, It's not important know that I know about it, and I rarerly boot from thumb drive, BTW, this does not happen with a "normal" external like a Seagate, only the thumb drive. Thanks for the explanation.

**Comment by dakanji** [comment]
Converting to an Improvement Item.

Will still be there for now, but will look at trying to reduce the cases where it is actually observed.
