### ISSUE TITLE
Unable to Boot Legacy Windows (Bootcamp)

### ISSUE THREAD

**Issue by ehDub** [dakanji/RefindPlus#114]
### RefindPlus Version

v0.13.3.AA Release

### Device Type

Apple Mac

### Problem Description

Otherwise bootable Bootcamp as picker selection leads to verbose in photo and grey screen
![APFS?verbose](https://user-images.githubusercontent.com/26954849/173209451-1a87abce-aae8-48f0-b971-6649867c0de3.jpg)
.

### Problem Point

While starting a loader or tool

### Affected Items

WinOS Loader

### Debug Log

MyBootMgr to Legacy (BIOS) Loader is the best I can do at present [MBM.log](https://github.com/dakanji/RefindPlus/files/8884954/MBM.log)

**Comment by dakanji** [comment]
Looks like a BootCamp specific issue given the odd APFS messages.

Queries:
1. Which bay/slot is the BootCamp disk connected to?
2. Does BootCamp sit alone on a disk or does it share with some other OS?
3. If not directly connected to one of the native SATA bays, what type of adapter is being used if any?
4. How did you set BootCamp up and which MacOS version was used?
5. Your log appears to have come from a MacPro3,1 with the firmware flashed for NVME and APFS ... How exactly did you flash the APFS as in which procedure did you follow?

**Comment by ehDub** [comment]
thanks Dayo, I'm hoping it's something to do with invalid GPT I don't yet understand. I've read this is somehow created inadvertently by BootCamp Assistant and can thwart installs so I'll see what I can do to rectify it.
1. Bay 4
2. N/A
3. BootCamp is whole MBR drive
4. Not sure, DD Catalina most likely possibly High Sierra BC Assistant who I think is responsible for the invalid GPT 
5. Yes 3.1, Firmware procedure here https://www.youtube.com/watch?v=NeSxwn2teW8
6.  shots...
![Screen Shot 2022-06-12 at 9 42 12 PM](https://user-images.githubusercontent.com/26954849/173227828-3fbe5aab-2aaf-4821-803c-4107cf749fc9.jpg)
![Screen Shot 2022-06-12 at 9 52 47 PM](https://user-images.githubusercontent.com/26954849/173227855-0270f112-918f-4505-98e3-552f30638b0f.jpg)
s

**Comment by dakanji** [comment]
Perhaps someone like @startergo or @joevt can advise on the implications of, and/or solutions to (if required), the invalid GPT notice.

**Comment by dakanji** [comment]
> I think it's safe to assume this is disk/pilot error

Just noticed this ... Does it mean you want the issue to be closed?

**Comment by ehDub** [comment]
Yes if it's a bother, reading this below I'm optimistic and glad RefindPlus alerted me to the problem.  http://www.rodsbooks.com/gdisk/repairing.html

**Comment by startergo** [comment]
It is not detecting valid GPT. Ideally legacy boot on the same disk should be marked as hybrid MBR. In reality it is a GPT disk but the EFI is obfuscated for Windows so the windows sees the disk as MBR. Theoretically it can be converted to Hybrid GPT/MBR with gdisk, but I recommend doing a backup beforehand.

**Comment by dakanji** [comment]
Adding the `ExFatDxeLegacy` driver might help with detecting Bootcamp as this might have been a factor.
This driver is now added when configuring with MyBootMgr as from v082.

**Comment by joevt** [comment]
Use my script at https://gist.github.com/joevt/a99e3af71343d8242e0078ab4af39b6c to gather MBR/GPT details for legacy boot issues.
