### ISSUE TITLE
Please implement allow_boot_symlinks in next release

### ISSUE THREAD

**Issue by MarioG-X** [dakanji/RefindPlus#120]
### Suggested Feature

The other issue is locked to I can't update it.

Since converting to OpenSuse Tumbleweed there are kernel updates weekly. This is a real inconvenience since I have to copy files to get RP to find them for each update. The upstream request you made will most likely take a very long time if at all. The allow_boot_symlinks option you added to the test RP works fine so please add that t the next RP release. Thanks!

### Background Information

Request to add option added from previous test RP to release.

**Comment by dakanji** [comment]
> The other issue is locked to I can't update it.

You can use the discussions feature to update locked thereads.

Anyway, this one was already in the pipeline and was about to be pushed here.
