### ISSUE TITLE
RefindPlus Hangs when Hybrid MBR Disk (Mac OS and BootCamp) is Present

### ISSUE THREAD

**Issue by tjthrush** [dakanji/RefindPlus#121]
### RefindPlus Version

v0.13.3.AA Release

### Device Type

Apple Mac

### Problem Description

softbless into RP with a boocamp SSD (containing macOS 10.9.5 & win7) creates a RP page that never populates.

remove the disk (from a MacPro 5,1) and it works fine. able to OC to big sur and boot into default mojave ssd.

big sur is on an NVME blade. 

### Problem Point

Other

### Affected Items

All OS Loaders (First Row Items)

### Debug Log

Sorry, new to this. Where are the logs located?

**Comment by dakanji** [comment]
> Where are the logs located?

MyBootMgr guide:
![000-logs](https://user-images.githubusercontent.com/1128876/187318679-8b93062c-9da6-4c6e-a881-c9d12fa9c951.JPG)

**Comment by tjthrush** [comment]
[22p29x2137.log](https://github.com/dakanji/RefindPlus/files/9448548/22p29x2137.log)
[22p29z2907.log](https://github.com/dakanji/RefindPlus/files/9448549/22p29z2907.log)

Do you need OC logs as well?

**Comment by dakanji** [comment]
> Do you need OC logs as well?

No. It is a RefindPlus issue.

Will take a look and get back later.
Thanks

**Comment by dakanji** [comment]
Please replace your current BOOTx64.efi file with the attached X252.
[X252-BOOTx64.efi.zip](https://github.com/dakanji/RefindPlus/files/9449051/X252-BOOTx64.efi.zip)

That is change the current file to something like `BOOTx64.efix` to disable it and rename the attached as `BOOTx64.efi` then reboot and share the new log from a boot with the problem disk attached.

The file does not contain any attempted fixes and is just a build that produces detailed logs. That is, it will similarly hang and this will need to be aborted and the disk disconnected as before. As it produces detailed logs, it is a lot slower and you will need to wait a while before aborting the boot.

**Comment by tjthrush** [comment]
[22p30r5926.log](https://github.com/dakanji/RefindPlus/files/9454570/22p30r5926.log)

**Comment by tjthrush** [comment]
Done

**Comment by tjthrush** [comment]
Like I said, new to GitHub

**Comment by dakanji** [comment]
Please run X253 in the same manner
Wait for about 5 mins before aborting the run

[X253-BOOTx64.efi.zip](https://github.com/dakanji/RefindPlus/files/9458549/X253-BOOTx64.efi.zip)

**Comment by tjthrush** [comment]
Done
[22p31t0030.log](https://github.com/dakanji/RefindPlus/files/9463524/22p31t0030.log)

**Comment by tjthrush** [comment]
Forgot to wait a full 5 min. Want me to redo or did you get what you want?

**Comment by dakanji** [comment]
Looks fine.

Please try X254
[X254-BOOTx64.efi.zip](https://github.com/dakanji/RefindPlus/files/9464254/X254-BOOTx64.efi.zip)

**Comment by tjthrush** [comment]
Full 5min this time
[22p31v5237.log](https://github.com/dakanji/RefindPlus/files/9464675/22p31v5237.log)

**Comment by dakanji** [comment]
Thanks. Please give X255 a try
[X255-BOOTx64.efi.zip](https://github.com/dakanji/RefindPlus/files/9464996/X255-BOOTx64.efi.zip)

**Comment by dakanji** [comment]
Yes. Best delete the logs once posted.
You may also want to clear the trash when the ESP is mounted

**Comment by tjthrush** [comment]
Thank you again or the support you provide the Mac community

**Comment by dakanji** [comment]
All the logs are returning gibberish.

The issue seems to be tied to your drives all being hybrid MGR (not sure why you have them all set up in this way).

RefindPlus does not have issues with most of them but something seems to have gone haywire on the disk with the BootCamp instance and my suggestion is that you consider sticking with either GPT or MGR for each disk.

Put BootCamp on its own MBR disk and your Mac OS instances on GPT disks and do not mix Legacy MBR with UEFI GPT on the same disk. It is obviously possible but seems to be the source of the issues.

As said, the Mac OS disks without BootCamp as also hybrids but they would be better as GPT in my view.

I know @joevt found a shortcoming in the `DirIterXYZ` code but I haven't yet gotten my head around what he did. This might be related to why RefindPlus is struggling with the disk. Will need time to investigate. Perhaps save this problem disk for further investigation later and install WIndows and the Mac OS on other disks if possible. To repeat, I would suggest making the other Mac OS instances on hybrid disks all pure GPT.

@startergo posts a lot of stuff about hybrid MBR but I don't understand half of what he posts on that. He might be able to chip in with more of the same here!

This [issue](https://github.com/dakanji/RefindPlus/issues/114) and [this one](https://github.com/dakanji/RefindPlus/issues/119) may be worth looking at. The first one has a link to upstream documentation that may be of interest.

**Comment by tjthrush** [comment]
>all being hybrid MBR (not sure why you have them all set up in this way).
I didn't set them up this way. I noticed this in the log as well. Could selecting the AHCI method in ConfigFactory be converting ALL the volumes?

Is there a quick way of testing this short of restarting the process and choosing the latest Innie 1.3 (?) method for showing NVME blades as internal?

I'll review the refs you provided to see if my hypothesis has any validity

**Comment by tjthrush** [comment]
sorry, part of my response got merged w/ your comment:

I didn't set them up this way. I noticed this in the log as well. Could selecting the AHCI method in ConfigFactory be converting ALL the volumes?

**Comment by dakanji** [comment]
ConfigFactory amends the config files for RefindPlus and OpenCore. It does not format disks.

Showing a disk as internal is a cosmetic thing done AFTER you have first selected OpenCore and then in OpenCore, selected a Mac OS instance to boot into.

BootCamp creates hybrid MBR as that is how it gets Windows to work with Mac OS. The most likely scenario, given that you have not specifically created these in this way, is that you have had BootCamp on the disks at one point or another.

**Comment by dakanji** [comment]
See title.

Assumption is that one specific hybrid MBR disk got corrupted and causes RP to hang when connected.

**Comment by startergo** [comment]
You may want to use gdisk to inspect the disk layout in question. See here for details:
https://forums.macrumors.com/threads/cmp5-1-and-apple-bootcamp-assistant-for-creating-windows-10-partition.2235132/post-28453741

**Comment by dakanji** [comment]
@tjthrush ... please try X256 as before:
[X256-BOOTx64.efi.zip](https://github.com/dakanji/RefindPlus/files/9475044/X256-BOOTx64.efi.zip)

In terms of inspecting the disk, you could also check this by first using `diskutil list` to get the Disk ID and then running `sudo gpt -r show /dev/disk1` where `/dev/disk1` is replaced by the actual Disk ID.

To post blocks of text here, put triple backticks before and after the block of text as shown below:

>\`\`\`
>Line 1
>Line 2
>Line n
>\`\`\`

**Comment by tjthrush** [comment]
...
/dev/disk6 (internal, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *240.1 GB   disk6
   1:                        EFI EFI                     209.7 MB   disk6s1
   2:                  Apple_HFS TTs 180                 180.0 GB   disk6s2
   3:                 Apple_Boot Recovery HD             784.2 MB   disk6s3
   4:       Microsoft Basic Data BOOTCAMP                59.1 GB    disk6s4

TTs-Hex:~ tthrush$ sudo gpt -r show /dev/disk6
Password:
gpt show: /dev/disk6: Suspicious MBR at sector 0
      start       size  index  contents
          0          1         MBR
          1          1         Pri GPT header
          2         32         Pri GPT table
         34          6         
         40     409600      1  GPT part - C12A7328-F81F-11D2-BA4B-00A0C93EC93B
     409640  351562496      2  GPT part - 48465300-0000-11AA-AA11-00306543ECAC
  351972136    1531680      3  GPT part - 426F6F74-0000-11AA-AA11-00306543ECAC
  353503816       1464         
  353505280  115355648      4  GPT part - EBD0A0A2-B9E5-4433-87C0-68B6B72699C7
  468860928       1167         
  468862095         32         Sec GPT table
  468862127          1         Sec GPT header
...

**Comment by tjthrush** [comment]
Sorry

```
/dev/disk6 (internal, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *240.1 GB   disk6
   1:                        EFI EFI                     209.7 MB   disk6s1
   2:                  Apple_HFS TTs 180                 180.0 GB   disk6s2
   3:                 Apple_Boot Recovery HD             784.2 MB   disk6s3
   4:       Microsoft Basic Data BOOTCAMP                59.1 GB    disk6s4

TTs-Hex:~ tthrush$ sudo gpt -r show /dev/disk6
Password:
gpt show: /dev/disk6: Suspicious MBR at sector 0
      start       size  index  contents
          0          1         MBR
          1          1         Pri GPT header
          2         32         Pri GPT table
         34          6         
         40     409600      1  GPT part - C12A7328-F81F-11D2-BA4B-00A0C93EC93B
     409640  351562496      2  GPT part - 48465300-0000-11AA-AA11-00306543ECAC
  351972136    1531680      3  GPT part - 426F6F74-0000-11AA-AA11-00306543ECAC
  353503816       1464         
  353505280  115355648      4  GPT part - EBD0A0A2-B9E5-4433-87C0-68B6B72699C7
  468860928       1167         
  468862095         32         Sec GPT table
  468862127          1         Sec GPT header
```

**Comment by tjthrush** [comment]
here's where my ESP is located:

```
TTs-Hex:~ tthrush$ sudo gpt -r show /dev/disk1
Password:
      start       size  index  contents
          0          1         PMBR
          1          1         Pri GPT header
          2         32         Pri GPT table
         34          6         
         40     409600      1  GPT part - C12A7328-F81F-11D2-BA4B-00A0C93EC93B
     409640  976433240      2  GPT part - 48465300-0000-11AA-AA11-00306543ECAC
  976842880     262147         
  977105027         32         Sec GPT table
  977105059          1         Sec GPT header
```

**Comment by dakanji** [comment]
Nothing unusual there. Suspicious MBR is because of the hybrid setup.
Please try the 256 file.

PS. You can access the edit option by clicking the three horizontal dots

**Comment by tjthrush** [comment]
As before, left for 5min and came back to colors cycling on my screen. Hit the space key and RefindPlus was up. Selected bootcamp volume and successfully booted. Finally shutdown once fully booted. Well done!!

[22r02x3319.log](https://github.com/dakanji/RefindPlus/files/9481221/22r02x3319.log)

**Comment by startergo** [comment]
> Sorry
> 
> ```
> /dev/disk6 (internal, physical):
>    #:                       TYPE NAME                    SIZE       IDENTIFIER
>    0:      GUID_partition_scheme                        *240.1 GB   disk6
>    1:                        EFI EFI                     209.7 MB   disk6s1
>    2:                  Apple_HFS TTs 180                 180.0 GB   disk6s2
>    3:                 Apple_Boot Recovery HD             784.2 MB   disk6s3
>    4:       Microsoft Basic Data BOOTCAMP                59.1 GB    disk6s4
> 
> TTs-Hex:~ tthrush$ sudo gpt -r show /dev/disk6
> Password:
> gpt show: /dev/disk6: Suspicious MBR at sector 0
>       start       size  index  contents
>           0          1         MBR
>           1          1         Pri GPT header
>           2         32         Pri GPT table
>          34          6         
>          40     409600      1  GPT part - C12A7328-F81F-11D2-BA4B-00A0C93EC93B
>      409640  351562496      2  GPT part - 48465300-0000-11AA-AA11-00306543ECAC
>   351972136    1531680      3  GPT part - 426F6F74-0000-11AA-AA11-00306543ECAC
>   353503816       1464         
>   353505280  115355648      4  GPT part - EBD0A0A2-B9E5-4433-87C0-68B6B72699C7
>   468860928       1167         
>   468862095         32         Sec GPT table
>   468862127          1         Sec GPT header
> ```

You  might have this partition borked. 
try downloading [gdisk](https://sourceforge.net/projects/gptfdisk/):

```
sudo gdisk /dev/disk6
```
and use command ```p``` at the prompt

**Comment by tjthrush** [comment]
Any borking present?

```
TTs-Hex:~ tthrush$ sudo gdisk /dev/disk6
Password:
GPT fdisk (gdisk) version 1.0.9

Warning: Devices opened with shared lock will not have their
partition table automatically reloaded!
Partition table scan:
  MBR: hybrid
  BSD: not present
  APM: not present
  GPT: present

Found valid GPT with hybrid MBR; using GPT.

Command (? for help): p
Disk /dev/disk6: 468862128 sectors, 223.6 GiB
Sector size (logical): 512 bytes
Disk identifier (GUID): EF9D7E2F-F18F-425C-96C5-D705CF3D6E2A
Partition table holds up to 128 entries
Main partition table begins at sector 2 and ends at sector 33
First usable sector is 34, last usable sector is 468862094
Partitions will be aligned on 8-sector boundaries
Total free space is 2637 sectors (1.3 MiB)

Number  Start (sector)    End (sector)  Size       Code  Name
   1              40          409639   200.0 MiB   EF00  EFI System Partition
   2          409640       351972135   167.6 GiB   AF00  TTs 240G
   3       351972136       353503815   747.9 MiB   AB00  Apple_HFS_Untitled_2
   4       353505280       468860927   55.0 GiB    0700  BOOTCAMP

Command (? for help): 
```

**Comment by startergo** [comment]
What is the output from:
```
sudo fdisk /dev/disk6
```

**Comment by tjthrush** [comment]
```
TTs-Hex:~ tthrush$ sudo fdisk /dev/disk6
Password:
Disk: /dev/disk6	geometry: 29185/255/63 [468862128 sectors]
Signature: 0xAA55
         Starting       Ending
 #: id  cyl  hd sec -  cyl  hd sec [     start -       size]
------------------------------------------------------------------------
 1: EE 1023 254  63 - 1023 254  63 [         1 -     409639] <Unknown ID>
 2: AF 1023 254  63 - 1023 254  63 [    409640 -  351562496] HFS+        
 3: AB 1023 254  63 - 1023 254  63 [ 351972136 -    1531680] Darwin Boot 
*4: 07 1023 254  63 - 1023 254  63 [ 353505280 -  115355648] HPFS/QNX/AUX
```

**Comment by startergo** [comment]
The disk looks fine to me.

**Comment by dakanji** [comment]
> TTs-Hex:~ tthrush$ sudo fdisk /dev/disk6

Whenever you run commands that take a Disk ID, note that as it can change between reboots and that you need to confirm the ID if you have rebooted that machine since your last check. 

Doesn't seem to have been the case with the above but just be aware that it can happen and that this would pipe the commands to a totally different item. This is particularly important when running destructive stuff.

Anyway, please try X257 as before
[X257-BOOTx64.efi.zip](https://github.com/dakanji/RefindPlus/files/9482726/X257-BOOTx64.efi.zip)

**Comment by tjthrush** [comment]
Stayed and watched this time. RefindPlus w/ blank screen for approx 45sec and then populated w/ bootcamp volume already selected. Unlike Boot Runner (that I used previously before finding RefindPlus as a replacement), 5,1 didn't need reboot into windows, just went right to starting win7. Once booted left sitting until 5min was up and shutdown.
[22r03t1618.log](https://github.com/dakanji/RefindPlus/files/9483098/22r03t1618.log)

**Comment by dakanji** [comment]
Will push the fix into the next release. Thanks.
Notwithstanding this, you will be well served by attending to your disks.

Stage 1:
- Use the TweakESP app from MyBootMgr to mount each ESP on every disk in turn
- Delete any extra files in each ... log files etc
- Empty the trash with the ESP mounted before moving to the next one

Stage 2:
- Set Mac OS to show hidden files by pressing the `cmd + shift + period` keys
- Use the TweakESP app from MyBootMgr to mount each ESP on every disk in turn
- Delete any extra files in each ... `trashes`, `spotlight` etc
- Empty the trash with the ESP mounted before moving to the next one (If trash is populated)

Ultimately:
- Get a new SSD
- Get a copy of Carbon Copy Cloner (There is a free trial but every Mac OS user should buy it)
- Format the disk as GPT and clone one of your Mac OS disks to this
- Test the new instance 
- If fine, reformat the original and start over for another of your disks
- Repeat until all your Mac OS instances are on newly formatted disks 

You will be left with a disk with the Hybrid MBR and a spare disk. Format that as MBR and move Windows there or if you do not specifically need Windows 7, install Windows 10 by following this process which dispenses with BootCamp and Hybrid MBR: https://forums.macrumors.com/threads/2250317

Will consider this a RefindPlus bug but Hybrid MBR can be a PITA. You can read up on the gory details here: https://www.rodsbooks.com/gdisk/hybrid.html.
