### ISSUE TITLE
MacOS Ventura manual Reboot / Shutdown issue (if chainloading OpenCore 0.8.5)

### ISSUE THREAD

**Issue by billabongbruno** [dakanji/RefindPlus#124]
### RefindPlus Version

v0.13.3.AB Release

### Device Type

UEFI PC

### Problem Description

When chainloading OpenCore 0.8.5, I get the "Your computer has restarted because of a problem" error message everytime I boot up MacOS Ventura (final version, not Beta) upon a manual reboot or shutdown.

If I boot OpenCore directly (rather than chainloading via refindplus), this issue does not occur. (So it's not an OpenCore issue).

### Problem Point

After starting a loader or tool

### Affected Items

OpenCore Loader

### Debug Log

No log provided, as it only affects a chainloaded tool.
refindplus itself loads perfectly.

Will provide one if needed.

### Additional Context

This issue did not take place with MacOS BigSur nor MacOS Monterey.

**Comment by dakanji** [comment]
> No log provided, as it only affects a chainloaded tool.

Logs are required regardless  ... from both RefindPlus and OpenCore.

**Comment by billabongbruno** [comment]
Apologies.
I've been away because of work and have failed to check for activity.

I will use refindplus' debug release to generate a log, as well as OpenCore's.

I'll post it here as soon as I get the chance.

For now I will be closing this, just so it isn't pending.

Thank you.

**Comment by billabongbruno** [comment]
@dakanji , figured out my issue is not refindplus related, but rather VoodooInput.kext.

Sorry for the bother.

Thank you for you great work.
