### ISSUE TITLE
Recent versions log finding MBR partitions when there is none

### ISSUE THREAD

**Issue by MarioG-X** [dakanji/RefindPlus#131]
### RefindPlus Version

v0.13.3.AC Release

### Device Type

Apple Mac

### Problem Description

My 2 Macs are partitioned as GPT with no MBR hybrid. I used Gparted, etc. to verify. These drives were wiped clean and formatted as GPT long ago. Starting with RP AB, and now AC, the log contains:
"**Found MBR Partition Table on Disk Entry Below:**"
for the 2 internal disks (SSD and HD). I tested AA, AB, and AC, and the line did not show up in AA, so this started in AB.

### Problem Point

While starting a loader or tool

### Affected Items

All OS Loaders (First Row Items)

### Debug Log

[AA.log](https://github.com/dakanji/RefindPlus/files/10188013/AA.log)
[AB.log](https://github.com/dakanji/RefindPlus/files/10188014/AB.log)
[AC.log](https://github.com/dakanji/RefindPlus/files/10188015/AC.log)

### Additional Context

I found this while working on why I see a whole disk entry on RP (see discussions) for a USB. That USB shows 
"Found Legacy Boot Code and Found MBR Partition Table on Disk Entry Below:"
but I can't find where that is, unlike the internal disks, this line shows up in AA. May be unrelated to this issue.

**Comment by MarioG-X** [comment]
Further examination in linux shows: parted, sfdisk, and fdisk showed as GPT. However, gdisk contained a line as "MBR: Protective". So this may have been missing in AA and fixed in AB, in which case this issue is closed.

**Comment by dakanji** [comment]
This appears to be how things are set up to work from upstream. May look at it at it further at some point.

**Comment by dakanji** [comment]
> This appears to be how things are set up to work from upstream. May look at it at it further at some point.

On the specific issue raised here, which is that logging shows up, this is simply because the logging was fixed in the mentioned version (it was not logging that action before due to formatting issues).

**Comment by MarioG-X** [comment]
I am closing because I believe that AA was not displaying the Protective MBR that was always there, then fixed in AB. I only thought this may have been an issue while working on the "whole disk" extra menu item which it turns out had nothing to do with this.

**Comment by dakanji** [comment]
REF: https://github.com/dakanji/RefindPlus/discussions/130
