### ISSUE TITLE
The "decline_esp_filter" config setting is the wrong way round

### ISSUE THREAD

**Issue by MarioG-X** [dakanji/RefindPlus#135]
### RefindPlus Version

v0.13.3.AC Release

### Device Type

Apple Mac

### Problem Description

When there are multiple drives available to boot, in this case an internal SSD and HD, both containing an EFI partition. RP only scans the first one it finds. They were originally the same name "EFI" and I tested renaming to "EFI0" and "EFI1" and it made no difference. 

I found this because RP and OC is installed into the EFI folder on an iMac and it works fine, RP displays the OC entry, but on the Mini, OC is not found. The difference is the sequence of the internal SSD and HD. Three logs below show both machines and before/after rename.

The workaround I have found is to copy OC to the only EFI that RP finds, and RP displays the entry and works.

### Problem Point

Before starting a loader or tool

### Affected Items

OpenCore Loader, Other Item

### Debug Log

This log is of the iMac that works fine, RP displays the OC entry, note is still only scans one volume, but the one with OC:
[22x15v0838.log](https://github.com/dakanji/RefindPlus/files/10240087/22x15v0838.log)

This log is from the Mini that does not display OC which resides in the same EFI directory as RP, note it only scans one of the EFI volumes:
[22x15v1155.log](https://github.com/dakanji/RefindPlus/files/10240105/22x15v1155.log)

This is the log after I renamed the EFI volumes to different names, note it does not scan EFI0:
[22x15v2116.log](https://github.com/dakanji/RefindPlus/files/10240112/22x15v2116.log)

**Comment by dakanji** [comment]
Please read up on the config options or/and the readme here.
Ref: `decline_esp_filter`

**Comment by MarioG-X** [comment]
Added decline_esp_filer, still no go, will not look t right refi for OC. Here is log and config.
[22x16c2118.log](https://github.com/dakanji/RefindPlus/files/10242129/22x16c2118.log)
[config.txt](https://github.com/dakanji/RefindPlus/files/10242132/config.txt)

**Comment by dakanji** [comment]
There is a different bug on that in that `decline_esp_filter` is working the wrong way round.
You need to uncomment it and add `false` to read `decline_esp_filter false`

This is an "incorrect" setting btw but is what will work until fixed.

**Comment by MarioG-X** [comment]
That worked like a charm. Thanks! You can leave issue open or close based on your fix.
