### ISSUE TITLE
Use Exact String Match for Default Selection 

### ISSUE THREAD

**Issue by MarioG-X** [dakanji/RefindPlus#137]
### RefindPlus Version

v0.13.3.AC Release

### Device Type

Apple Mac

### Problem Description

This was a problem that you previously fixed and I can't find the issue. It think it had to do with generic lookup of volume names. I have a volume named "FS Monterey Ubiquiti" which is before volume "FS Monterey". I never boot the Ubiquity volume but use the "FS Monterey" volume a lot. Each reboot RP selects "FS Monterey Ubiquiti" as the default, wrong volume. I know this was fixed at some point and may have not noticed it in AC until now when I am doing a lot of reboots per hour.

### Problem Point

Before starting a loader or tool

### Affected Items

Other Item

### Debug Log

[22x15z4032.log](https://github.com/dakanji/RefindPlus/files/10241547/22x15z4032.log)

**Comment by dakanji** [comment]
Please give your volumes unique names that do not match parts of other volumes.

**Comment by MarioG-X** [comment]
Here the kicker: This was working perfectly in AB and I think AC. I even re-installed AB with it's config and it does not work anymore. I thought it was because I added OC so I took it out to test and it still does not work correctly. Anyway it was a minor issue you had fixed this year and probably not worth the time I guess if no one else mentions it.

I will live with it since its easier to always tab than to make non-meaningful names to satisfy a simple default.

**Comment by dakanji** [comment]
It is not an issue but how rEFInd and RefindPlus work.
I had looked into amending RefindPlus to accommodate this but it came with a performance and reliability penalty.

You can tab each time as you said or resolve things by simply naming your volumes such that they don't match as a substring of another.

**Comment by dakanji** [comment]
> its easier to always tab than to make non-meaningful names to satisfy a simple default

Your call on this obviously but if `FS Monterey Ubiquiti` is not meaningless then `FS Monterey Main`, or similar, on the other must have the same status I would have thought.

In any case, I will look into accommodating this.

**Comment by MarioG-X** [comment]
Forgot to mention I have backup scripts programmed for simple naming conventions so way easier to tab than change them. Thanks, still strange it was working perfect with these exact names last week.
