### ISSUE TITLE
Forced Default Config Settings Are Sometimes Skipped 

### ISSUE THREAD

**Issue by dakanji** [dakanji/RefindPlus#138]
### RefindPlus Version

v0.13.3.AC Release

### Device Type

UEFI PC, Apple Mac, Chromebook, Other Device

### Problem Description

Forced default configuration settings, typically based on firmware type, are only set when the affected setting is being specifically set but should always be set.

### Problem Point

Other

### Affected Items

Other Item

### Debug Log

N/A

**Comment by startergo** [comment]
Tested release version. Just hangs on the RP logo.

**Comment by dakanji** [comment]
Please raise an issue to properly report
