### ISSUE TITLE
Add support for multiple/tertiary supplementary config files

### ISSUE THREAD

**Issue by 1457384613gh** [dakanji/RefindPlus#142]
**Suggested Feature**

Support to include Several secondary .config files.

Example,

config.conf
`include mouse.conf`
`include icon.conf`
`include menuentry.conf`
`include A.conf`
`include B.conf`
`include C.conf`
`include …`

It's more convenient to break up the whole into parts.

**Background Information**

Or support several tertiary files.

Example,

config.conf
include setting.conf

include ….conf

**Additional Context**

Only one secondary file is not enough.

**Comment by 1457384613gh** [comment]
So, the next release will have this function?

**Comment by dakanji** [comment]
Sorry, but while I can see a lot of complexity needed in the code, I can't see what this actually brings to the table.
That is, you have not quite explained why it should be done.

I know you have said `It's more convenient to break up the whole into parts` and that `Only one secondary file is not enough.` but you haven't explained why it is more convenient to split the parts or why a secondary file is not enough.

What exactly would this permit that is not currently permitted?

**Comment by 1457384613gh** [comment]
Only one .config is too long.

If it supports several .config files, different types of configurations can be classified and archived.
And be shorter.

Grub supports more.

grub.cfg
`source /…/menuentry.cfg`
`source /…/theme.cfg`
`source …`

Every file is short, one or two effects.

**Comment by dakanji** [comment]
Sorry, but I cannot really see the benefit at this time.
If you can convince upstream to implement this however, then it will be added here.

Thanks for the suggestion regardless!

**Comment by 1457384613gh** [comment]
Do you mean rEFInd not plus?

Email Smith?

**Comment by dakanji** [comment]
Yes. rEFInd.
i suppose you can try emailing him

**Comment by dakanji** [comment]
> Could help to copy what I said and email Smith?

Sorry, but I can't advocate this. Perhaps you can find someone to help out on that.

You can also try posting on the rEFInd project discussion page. He is not so active on that but ultimately gets around to stuff. Might take some time but I wouldn't say this is a critical item in any case.

**Comment by 1457384613gh** [comment]
Yes, you can.

Email on my phone shows that "fail to send".

Our national policy does not allow sending private emails to foreigners

**Comment by dakanji** [comment]
> Our national policy does not allow sending private emails to foreigners

Wow. I didn't realise that.
He has an account here on GitHub: https://github.com/srs5694
You might be able to reach him there (even if via a different repo)

**Comment by 1457384613gh** [comment]
😭😭😭

**Comment by dakanji** [comment]
I know it is him.

If you don't mind, I will close this now.
Good luck!

**Comment by 1457384613gh** [comment]
By the way, I have tried, rEFInd support to include several secondary .conf files.
The compatibility of including .conf files is different from rEFInd.

**Comment by 1457384613gh** [comment]
Thank you!

**Comment by 1457384613gh** [comment]
By the way, this is my config for rEFInd.

https://github.com/1457384613gh/Bootloader-for-BlissOS

rEFInd works well, but RefindPlus has bugs with my config.

Could you help me see it?

**Comment by dakanji** [comment]
Please post your new question under Discussions

**Comment by dakanji** [comment]
> rEFInd does allow having a chain of config files but this is due to a bug that has been fixed in RefindPlus.
> The rEFInd documentation actually states that this is not allowed.

There is a bit of nuance to this.

rEFInd does not indeed allow tertiary configuration files as stated here:  https://github.com/dakanji/rEFInd/blob/master/refind.conf-sample#L562-L570 but this limitation does not actually work and is the bug fixed in RefindPlus.

Both rEFInd and RefindPlus however allow tertiary include files for manual stanzas.

So it is possible to have the following:

```
# Additional Config File
# Only one is allowed
include config2.conf

# Manual stanza include files
# Multiple are allowed
include manual_stanza_a.conf
include manual_stanza_b.conf
...
include manual_stanza_z.conf
```

Each of those manual stanza include can have more includes in them

PS: Never used this feature myself but the code supports this although this feature is not documented.

**Comment by 1457384613gh** [comment]
Yes, I do so.

It is another bug that makes me believe by mistake, that multiple secondary files are not supported.
