### ISSUE TITLE
RefindPlus Hangs if SubMenuEntry is Present in Manual Stanzas

### ISSUE THREAD

**Issue by 1457384613gh** [dakanji/RefindPlus#144]
### RefindPlus Version

v0.13.3.AC Release

### Device Type

UEFI PC

### Problem Description

The same .conf file.
It works on rEFInd, showing icons.
![X](https://user-images.githubusercontent.com/69227436/212013347-fde9fd50-5236-42a5-ab74-22637ad58412.png)

It cannot work on RefindPlus, showing no icons.
![X](https://user-images.githubusercontent.com/69227436/212013374-ad776e56-f41f-498f-86b7-f1dc0b2808f1.png)

### Problem Point

Before starting a loader or tool

### Affected Items

Other Item

### Debug Log

[23b12i0408.log](https://github.com/dakanji/RefindPlus/files/10399439/23b12i0408.log)

### Additional Context

[EFI.7z.pdf](https://github.com/dakanji/RefindPlus/files/10399453/EFI.7z.pdf)

It is a .7z file, with ".pdf" deleted.

**Comment by dakanji** [comment]
Please provide the attachment as a zip file and bit 7z as was requested.

**Comment by 1457384613gh** [comment]
> Please provide the attachment as a zip file and bit 7z as was requested.

**Comment by dakanji** [comment]
Thanks. Will have a look later.
Please try to follow what is written/requested. I have just deleted the log contents you pasted as although the template asks that you **should not** directly paste such logs and only attach them, you have instead attached **and** pasted!

**Comment by dakanji** [comment]
Please temporarily rename your current RefindPlus efi, replace with the attached file, and share the log produced after trying to boot this.
[X262-BOOTx64-NPT.zip](https://github.com/dakanji/RefindPlus/files/10400794/X262-BOOTx64-NPT.zip)


Please attach the log and do not paste.
Also, this does a lot of logging so give it extra time before stopping it.

Thanks

**Comment by 1457384613gh** [comment]
I am sorry but I haven't understood.

Should I download that .zip and use files into to try and catch logs?

**Comment by dakanji** [comment]
> Should I download that .zip and use files into to try and catch a log?

Correct.

**Comment by 1457384613gh** [comment]
[23b13i3449.log](https://github.com/dakanji/RefindPlus/files/10409729/23b13i3449.log)

**Comment by dakanji** [comment]
You complained elsewhere about having a config file that is too long but a big chunk of the length is made up of default manual stanzas that should be removed.

Note that having them with `disabled` does not mean they are not processed, especially when the disabled line is the last one in the stanza and not the first item as advised in the readme here (I suppose no one ever reads a README)

So, either remove all the disabled manual stanza (best option) or move the `disabled` line to be the first thing in the stanza.
Rerun the file and attach the log file after this.

The current log has too much junk info from those stanzas.

Thanks

**Comment by 1457384613gh** [comment]
But all is into config.conf .
There is no any "include abcd.conf" into config.conf.

Other .conf files have not been included into config.conf .

**Comment by dakanji** [comment]
I wasn't referring to that other issue but to this

> I edit refind.conf-sample

You left the sample manual stanza, handle them in one of the ways i outlined in my previous post.
That is, either remove them or put the `disabled` line in each as the first thing in the stanza

**Comment by 1457384613gh** [comment]
Thank you for your patience!
I will try.

**Comment by 1457384613gh** [comment]
[23b14m3813.log](https://github.com/dakanji/RefindPlus/files/10416474/23b14m3813.log)
[config.conf.txt](https://github.com/dakanji/RefindPlus/files/10416475/config.conf.txt)

I have deleted many words behind "#".
The config.conf is shorter, now.
But it still, I don't know how to express.

**Comment by dakanji** [comment]
The important things were the unused/disabled `menuentry` stanzas items.

There seems to be a memory conflict and this results in a hang.
Please try the attached X263 file and attach the log to better understand the issue.
[X263-BOOTx64-NPT.zip](https://github.com/dakanji/RefindPlus/files/10416914/X263-BOOTx64-NPT.zip)

**Comment by 1457384613gh** [comment]
Thank you for your patience!
I will try.

**Comment by 1457384613gh** [comment]
[23b15e0138.log](https://github.com/dakanji/RefindPlus/files/10419427/23b15e0138.log)

By the way, why do you have so many .efi files?
Is it easy for you to package .efi files?

**Comment by dakanji** [comment]
These are test builds. See the readme for a link to instructions on building RefindPlus.

Please try X264 and share the log: [X264-BOOTx64-NPT.zip](https://github.com/dakanji/RefindPlus/files/10419498/X264-BOOTx64-NPT.zip)

Thanks

**Comment by 1457384613gh** [comment]
[23b15f3632.log](https://github.com/dakanji/RefindPlus/files/10419552/23b15f3632.log)

What I think is that what you can help me is more than I can help you so who should say "Thanks" is me.

**Comment by dakanji** [comment]
The issue seems to be linked to `submenuentry`.
Can you delete all these submenu entries and rerun with the X264 file?

That is, leave the menuentry items but delete subsequently sections, test the file and share the log. 

Thanks

**Comment by 1457384613gh** [comment]
[23b15h1830.log](https://github.com/dakanji/RefindPlus/files/10419649/23b15h1830.log)

It shows logs after around ten seconds this time.

**Comment by dakanji** [comment]
That gives the first definitive pointer to the issue.
Will take a proper look later

**Comment by dakanji** [comment]
Please restore the `submenuentry` items, run the attached X265 file and share the log
[X265-BOOTx64-NPT.zip](https://github.com/dakanji/RefindPlus/files/10421077/X265-BOOTx64-NPT.zip)

**Comment by 1457384613gh** [comment]
[23b16e0037.log](https://github.com/dakanji/RefindPlus/files/10422407/23b16e0037.log)

**Comment by dakanji** [comment]
Thanks. Please try X266 on the same basis
[X266-BOOTx64-NPT.zip](https://github.com/dakanji/RefindPlus/files/10422731/X266-BOOTx64-NPT.zip)

**Comment by 1457384613gh** [comment]
[23b16g5030.log](https://github.com/dakanji/RefindPlus/files/10423253/23b16g5030.log)

Maybe something wrong around "add_options"

**Comment by dakanji** [comment]
Please try X267 on the same basis
[X267-BOOTx64-NPT.zip](https://github.com/dakanji/RefindPlus/files/10423983/X267-BOOTx64-NPT.zip)

**Comment by 1457384613gh** [comment]
[23b16j5110.log](https://github.com/dakanji/RefindPlus/files/10424628/23b16j5110.log)

**Comment by dakanji** [comment]
Getting warmer ... Please try X268
[X268-BOOTx64-NPT.zip](https://github.com/dakanji/RefindPlus/files/10425239/X268-BOOTx64-NPT.zip)

**Comment by 1457384613gh** [comment]
I will try tomorrow or the day after tomorrow.

**Comment by dakanji** [comment]
Nevermind. It hangs as well but know where the issue starts. I will push a fix soon presently.

**Comment by 1457384613gh** [comment]
I am going to download X268.
Where to download?

**Comment by 1457384613gh** [comment]
I am going to download X268.
Where to download?

**Comment by dakanji** [comment]
Refer to my previous.
No need for any further tests at this time.

**Comment by 1457384613gh** [comment]
So you are testing and trying to fix?

**Comment by dakanji** [comment]
Yes, but you only needed to read what I referred you to before to have seen this!

> ... know where the issue starts. I will push a fix presently.

**Comment by dakanji** [comment]
You need to build the codebase.
There is a link to build instructions in the ReadMe for this repo.

**Comment by dakanji** [comment]
If unable/unwilling to build, you will need to wait until release which will be whenever the codebase is deemed ready.
