### ISSUE TITLE
Load an external IntelGopDriver.efi

### ISSUE THREAD

**Issue by 1457384613gh** [dakanji/RefindPlus#147]
### Suggested Feature

I wish RefindPlus could support a higher resolution for my GPU.

![image](https://user-images.githubusercontent.com/69227436/213923710-120c5a02-30ea-4005-b2fe-c8e9adc7b6d7.png)

### Background Information

[CsmVideoDxe.efi] is from Clover, adapted from IntelGopDriver.efi .
[BiosVideo.efi] is from OpenCore, which can make [arrandale/ironlake] support a higher resolution.

I wish RefindPlus could load at least one of them, for my GPU.

### Additional Context

[efi_drivers.zip](https://github.com/dakanji/RefindPlus/files/10508872/efi_drivers.zip)

**Comment by dakanji** [comment]
Just attaching some random files and saying you wish RefindPlus will load them is of no use as an enhancement request.

**Comment by dakanji** [comment]
You wrote:
> I wish RefindPlus could load at least one of them

RefindPlus can load drivers as a basic functionality included from rEFInd. So, asking that this should be added shows you have not done basic investigation of using the tool or that there is something else you want, but have not provided basic information about this.
