### ISSUE TITLE
refind-ambience theme has a bug with selection_big

### ISSUE THREAD

**Issue by xCuri0** [dakanji/RefindPlus#150]
### RefindPlus Version

v0.13.3.AC Release

### Device Type

UEFI PC

### Problem Description

Screenshot using RefindPlus (wrong)
![ScreenShot_000](https://user-images.githubusercontent.com/29529557/218765291-e901c016-7549-4ffb-acec-782a13e2b169.png)

Screenshot using regular rEFInd (proper)
![image](https://user-images.githubusercontent.com/29529557/218765382-871aa462-10eb-4880-9f98-bd7b8ed8234d.png)

It appears that RefindPlus is using ```selection_small``` for ```selection_big```. Theme is [refind-ambience](https://github.com/lukechilds/refind-ambience) with wallpaper changed.

### Problem Point

Other

### Affected Items

All OS Loaders (First Row Items)

### Debug Log

[23d14r2212.log](https://github.com/dakanji/RefindPlus/files/10733944/23d14r2212.log)

**Comment by dakanji** [comment]
Thanks.

I understand what you mean but please attach a debug log after setting the `log_level` config token to `1`.

**Comment by xCuri0** [comment]
@dakanji Done. I think this points to the problem
```
. . . . . . . . ***[ Entering RunGenericMenu ]*** . . . . . . . .
   8:690    0:006  Running Menu Screen:- 'Main Menu'
                ***[ In egLoadFile ... Loaded File:- 'themes\refind-ambience\selection_small.png'
   8:698    0:008  Scaling Image to 85 x 85
   8:701    0:003  Scaling Image Completed
                ***[ In egLoadFile ... Loaded File:- 'themes\refind-ambience\selection_big.png'

* ** ** *** *** ***[ Discarding Input Big Selection Image ... Too Large ]*** *** *** ** ** *

   8:713    0:012  Scaling Selection Image from LoadedSmallImage
   8:716    0:003  Scaling Image to 288 x 288
   8:721    0:004  Scaling Image Completed
  11:030    2:309  Processing Keystroke: UnicodeChar = 0x0D ... ScanCode = 0x00 - INFER_ENTER    Key: CarriageReturn
  11:033    0:003  Returned '1' (ENTER) from RunGenericMenu Call on 'Boot Windows (UEFI) from EFI' in 'RunMainMenu'
```

**Comment by dakanji** [comment]
Right, what is going on there is that a kind of security audit flagged that images were being used without sanitising them for size which could apparently be an attack vector. I have therefore put an arbitrary limit of 256px on the longest side on the selection image to satisfy this

I will look into whether this is appropriate and already thinking to increase this (maybe double the size) but you can get past this in the interim if you could scale your image down to 256 x 256. Alternatively, if you are positioned to build your own, you can set the limit as you prefer here and build:
https://github.com/dakanji/RefindPlus/blob/329b441e3aa7a596ef7522810c7d0adfb7bed955/BootMaster/menu.c#L140
