### ISSUE TITLE
RefindPlus screen blank when using MyBootMgr v089a

### ISSUE THREAD

**Issue by tjthrush** [dakanji/RefindPlus#156]
### RefindPlus Version

v0.13.3.AC Release

### Device Type

Apple Mac

### Problem Description

using MyBootMgr v089a results in blank screen at boot. This occurs whether a Bootcamp disk is installed or removed

### Problem Point

RefindPlus fails to load

### Affected Items

Mac OS Loader

### Debug Log

[23d24x3825_v089a.log](https://github.com/dakanji/RefindPlus/files/10829137/23d24x3825_v089a.log)
[23d24x5101_v089a_no_BC.log](https://github.com/dakanji/RefindPlus/files/10829139/23d24x5101_v089a_no_BC.log)

**Comment by dakanji** [comment]
Thanks. Seems to be hanging.
Please try X276
[X276-BOOTx64.zip](https://github.com/dakanji/RefindPlus/files/10829251/X276-BOOTx64.zip)

**Comment by tjthrush** [comment]
Sorry Dayo it's been awhile, please confirm that I remove the current BOOTx64.efi file in the EFI/BOOT folder and replace with renamed X276 version?

**Comment by dakanji** [comment]
Correct

**Comment by tjthrush** [comment]
Works
[23d24z4209.log](https://github.com/dakanji/RefindPlus/files/10829815/23d24z4209.log)

**Comment by dakanji** [comment]
Great. This will be sorted for the next release.
We can now start looking at the other issue.

**Comment by tjthrush** [comment]
Thank you-
