### ISSUE TITLE
Like Clover, Support BIOS->MBR->PBR->boot->refindplus_x64.efi->OSLoader

### ISSUE THREAD

**Issue by 1457384613gh** [dakanji/RefindPlus#157]
# Suggested Feature

`CloverBootloader` has a special and great function, so I wonder whether you can bring such function to RefindPlus.

## Situations of CloverBootloader
**As is known to us**, it supports to be loaded by UEFI.
`UEFI->CLOVERX64.efi->OSLoader`
**What is amazing is that** it actually supports loaded by Legacy BIOS.
`BIOS->MBR->PBR->boot->CLOVERX64.efi->OSLoader`

    Bootdisk_Utility.exe can provide its MBR and PBR to achieve it.

So CloverBootloader can save old mainboards that support only Legacy BIOS without UEFI. CloverBootloader seems like an extended fake firmware that supports UEFI, which can make Legacy+BIOS load .efi files.
### Hope
We hope that RefindPlus would support so.
If you can provide MBR.bin and PBR.bin for Legacy BIOS loading refindplus_x64.efi or another_name_x64.efi, we will use them in place.
### Meanings

- If so, RefindPlus will make many old mainboards load .efi files, too.

- If so, we can use GPT disk for old mainboards with more than 4 primary partitions, because GPT disk has MBR and GPT partition has PBR too.

# Background Information

https://github.com/CloverHackyColor/CloverBootloader

# Additional Context

_No response_

**Comment by dakanji** [comment]
Thanks for the request.

RefindPlus allows using legacy bootcode to boot other items that use this but there are no plans to convert/add booting RefindPlus itself via legacy bootcode.

**Comment by dakanji** [comment]
Hi,

In future, please kindly raise separate items for separate issues.

The answer for this additional issue is the same as the first. That is, there is no plan to look into the subject at this time.
Since it is easy to do, you can make a PR and this will be considered.

**Comment by startergo** [comment]
You can do a PR to the rEFInd repo in sourceforge.
