### ISSUE TITLE
no boot screens on GTX 760

### ISSUE THREAD

**Issue by ahihi** [dakanji/RefindPlus#160]
### RefindPlus Version

v0.13.3.AD Release

### Device Type

Apple Mac

### Problem Description

using MyBootMgr v096, Mac Pro 3,1 with GTX 760 shows no boot screens in either RefindPlus or OpenCore. worked in v067a.

### Problem Point

Before starting a loader or tool

### Affected Items

Other Item

### Debug Log

linked below

### Additional Context

[macrumors thread](https://forums.macrumors.com/threads/refindplus-opencore-by-mybootmgr.2231693/post-32087309) with more info and logs

**Comment by dakanji** [comment]
Please test the attached X285 file by renaming and dropping into your RefindPlus setup to see if it resolves the issue.
[X285-BOOTx64.zip](https://github.com/dakanji/RefindPlus/files/11248626/X285-BOOTx64.zip)

Thanks

**Comment by ahihi** [comment]
yes! with this i do get boot screens.

**Comment by dakanji** [comment]
Thanks. Will clean up and push the fix presently.
We can look at the other issue in the meantime.
