### ISSUE TITLE
Ext4 driver does not scan all boot partitions

### ISSUE THREAD

**Issue by emperor06** [dakanji/RefindPlus#168]
### RefindPlus Version

v0.14.0.AA Release

### Device Type

UEFI PC

### Problem Description

When using the provided ext4_x64.efi driver, only the first ext4 partition is scanned for linux kernels.
The device has the following partitions:

1. ESP
2. ext4 -> kernel found
3. luks encrypted
4. ext4 -> not scanned
5. ext4 -> not scanned
6. ext4 -> not scanned

Using upstream's ext4_x64.efi driver, all 4 ext4 boot partitions are scanned and show up in the boot menu.

### Problem Point

Before starting a loader or tool

### Affected Items

Lin OS Loader

### Debug Log

[23p31i1639.log](https://github.com/dakanji/RefindPlus/files/12484378/23p31i1639.log)

**Comment by dakanji** [comment]
Thanks for the report.

Can you confirm you mean to say that when you use the provided driver with RefindPlus, some volumes are not scanned but when you use the upstream driver instead, they are?

If so, do you see the same behaviour running rEFInd?

**Comment by emperor06** [comment]
I confirm.

I've tried RefindPlus' driver with Refind and got the same problem: only the first ext4 partition was scanned.

I don't know if it stops scanning after one partition or if it stops because it reached a luks partition. I'll try to insert another small ext4 partition before luks.

(edit)
I inserted a new ext4 partition before luks, so now the device is:

1. fat32 (esp)
2. ext4 (distro 1)
3. ext4 (distro 2)
4. luks
5. ext4 (distro 3)
6. ext4 (distro 4)

Same issue, only distro 1 is shown in the boot menu.

**Comment by emperor06** [comment]
I don't know if it's important or not, but there's something weird in the boot logs.
At line 185, the first ext4 partition is referred to as `mjboot` (volume name), which corresponds to the file system label, while the other ext4 partitions are referred to as `DEBIAN_BOOT` or `ARCH_BOOT`, which is the GPT partition label.

Here's the result of blkid, if that helps.
[blkid.log](https://github.com/dakanji/RefindPlus/files/12495574/blkid.log)

**Comment by dakanji** [comment]
Bizarre. Will have try to wrap my head around the issue for a while.
Can you try a run without any Ext4 drivers and share the log?

**Comment by emperor06** [comment]
Sure. Here's the log without any drivers: [23r01q0611.log](https://github.com/dakanji/RefindPlus/files/12498763/23r01q0611.log)

(as a matter of fact, I was still using X321 on the first reboot, so I also have those [logs](https://github.com/dakanji/RefindPlus/files/12498765/23r01q0146.log) if needed)

**Comment by dakanji** [comment]
What is most likely happening if that it is only getting installed once and skipped on subsequent handles.

Will have to see if this is the case indeed and why if so.
Might take some time as need to check whether only with Ext4 or not.

**Comment by emperor06** [comment]
Let me know if you need anything.

**Comment by dakanji** [comment]
Can you try the attached version of the driver and see whether you get a different outcome?
[08_ext4.zip](https://github.com/dakanji/RefindPlus/files/12505077/08_ext4.zip)

**Comment by emperor06** [comment]
Same, only the first ext4 partition appears.

**Comment by dakanji** [comment]
I see. Thanks.
Will prepare another later

**Comment by dakanji** [comment]
Please try this one:
[900_ext2.efi.zip](https://github.com/dakanji/RefindPlus/files/12516224/900_ext2.efi.zip)

**Comment by emperor06** [comment]
No partition found/scanned at all.

[23r04w5423.log](https://github.com/dakanji/RefindPlus/files/12516680/23r04w5423.log)

**Comment by dakanji** [comment]
Hi ... Please try the attached.
[800-ext4.zip](https://github.com/dakanji/RefindPlus/files/12555477/800-ext4.zip)

Thanks

**Comment by emperor06** [comment]
Success! All my ext4 boot partitions appear as boot entry.  Very nice.
[23r08g3914.log](https://github.com/dakanji/RefindPlus/files/12556374/23r08g3914.log)

Thanks

**Comment by dakanji** [comment]
Thanks ... please try this one as well:
[801-ext4.zip](https://github.com/dakanji/RefindPlus/files/12556881/801-ext4.zip)

**Comment by emperor06** [comment]
801 also works, all partitions are found.
[23r08i3045.log](https://github.com/dakanji/RefindPlus/files/12557360/23r08i3045.log)

**Comment by dakanji** [comment]
Thanks. Will push the fixes for this and the other item later.

**Comment by dakanji** [comment]
Resolved as part of Commit https://github.com/dakanji/RefindPlus/commit/cf40b5a0b30929357eb1e8c9eb9cd757f7225b89
