### ISSUE TITLE
refind_linux.conf (kernel parameters) is not read

### ISSUE THREAD

**Issue by emperor06** [dakanji/RefindPlus#169]
### RefindPlus Version

v0.14.0.AA Release

### Device Type

UEFI PC

### Problem Description

When loading a linux kernel directly (not using efi chainloading), Refind tries to guess the kernel parameters. On some systems, those parameters cannot be guessed, so upstream's Refind tries to get those kernel parameters from `/boot/refind_linux.conf`.
One example is having the root filesystem in a luks container: the root and cryptdevice parameters have to be manually set somewhere.
When used as a direct drop-in replacement (keep the old `refind.conf` and replace `refind_x64.efi`), Refind+ didn't read this `refind_linux.conf` resulting in a boot failure. I've tried to go through all the new options in case it's now a feature that needs enabling but I couldn't find anything about it.

Does Refind+ support reading config from the /boot directory?

### Problem Point

While starting a loader or tool

### Affected Items

Lin OS Loader

### Debug Log

[23p31i5701.log](https://github.com/dakanji/RefindPlus/files/12484550/23p31i5701.log)

`Loading 'vmlinuz-6.5-x86_64' ... Load Options:- 'initrd=\initramfs-6.5-x86_64.img'`

**Comment by dakanji** [comment]
Try duplicating the file and rename as `refindplus_linux.conf` and let me know if it makes a difference.

**Comment by emperor06** [comment]
cp /boot/refind_linux.conf /boot/refindplus_linux.conf

Now RefindPlus freezes. The theme background image is displayed but no text, no icon, no boot option.

I've waited for a few seconds (timeout) but the default OS did not boot. Pressing Enter does not boot either. Ctrl+alt+del does not reboot. Hard reset/shutdown is required.

I did get a log, though.
[23r01i2455.log](https://github.com/dakanji/RefindPlus/files/12496190/23r01i2455.log)

**Comment by dakanji** [comment]
Thanks. Please try the attached X319 build:
[X319-BOOTx64.zip](https://github.com/dakanji/RefindPlus/files/12497315/X319-BOOTx64.zip)

**Comment by emperor06** [comment]
I've tried with RefindPlus and Refind ext4 drivers, with and without refindplus_linux.conf. None of the 4 attempt worked. They all display the theme background then freeze.

- refind ext4, refindplus_linux.conf [23r01m2404.log](https://github.com/dakanji/RefindPlus/files/12497435/23r01m2404.log)
- refind ext4, refind_linux.conf [23r01m2641.log](https://github.com/dakanji/RefindPlus/files/12497443/23r01m2641.log)
- refindplus ext4, refindplus_linux.conf [23r01m2914.log](https://github.com/dakanji/RefindPlus/files/12497448/23r01m2914.log)
- refindplus ext4, refind_linux.conf [23r01m3038.log](https://github.com/dakanji/RefindPlus/files/12497455/23r01m3038.log)

**Comment by dakanji** [comment]
Thanks. Will review and get back.
Not looking at the driver issue here btw.

**Comment by dakanji** [comment]
Please run X320, which activates more detailed logging, and share the log.
Ignore the driver issue and just use the one that ordinarily works.
[X320-BOOTx64.zip](https://github.com/dakanji/RefindPlus/files/12497584/X320-BOOTx64.zip)

Thanks

**Comment by emperor06** [comment]
Still freezes at start.
Here's the log.
[23r01n0429.log](https://github.com/dakanji/RefindPlus/files/12497691/23r01n0429.log)

**Comment by dakanji** [comment]
Thanks. Please repeat with X321
[X321-BOOTx64.zip](https://github.com/dakanji/RefindPlus/files/12498057/X321-BOOTx64.zip)

**Comment by emperor06** [comment]
That's a victory. The UI is working again and I could boot using the correct kernel parameters.
Thanks a lot!

[23r01p4713.log](https://github.com/dakanji/RefindPlus/files/12498574/23r01p4713.log)

**Comment by dakanji** [comment]
Thanks for the report and tests.

You can build RefindPlus after the next commit or wait for the next release.

**Comment by dakanji** [comment]
Resolved as part of Commit https://github.com/dakanji/RefindPlus/commit/cf40b5a0b30929357eb1e8c9eb9cd757f7225b89
