### ISSUE TITLE
Mac OS installations not appearing in RefindPlus boot picker

### ISSUE THREAD

**Issue by CornCat78** [dakanji/RefindPlus#17]
**Describe the bug**
After installing RefindPlus per instructions, boot picker does not show native Mac OS (Mojave) installation.  I only see two OpenCore options (default and alternate).

**To Reproduce**
N/A

**Expected behaviour**
Mac OS volume should be available in boot picker after soft bless reboot.

**Environment:**
 - RefindPlus Version: v0.12.0.AN 
 - Hardware: Mac Pro 5,1. Vega 64. Dual 3.46 Xeon CPUs. 128gb RAM. Mojave APFS boot volume located on OWC 6g PCIe SSD card.
 - OS: Mojave 10.14.6 (18G7016)

**Log and Config Files**
[21b21x4313.log](https://github.com/dakanji/RefindPlus/files/5852630/21b21x4313.log)
[MyBootMgrOld.zip](https://github.com/dakanji/RefindPlus/files/5852642/MyBootMgrOld.zip)

**Screenshots**
![refindplus_bootpicker](https://user-images.githubusercontent.com/77812799/105424358-377dec00-5c15-11eb-8441-f8a87baf9cdf.jpg)

**Additional context**
N/A

**Comment by dakanji** [comment]
I see you have resolved the issue by selecting correct options in the tool provided in MyBootMgr.

**Comment by dakanji** [comment]
On reflection, I think you might have been affected by a bug that has now been fixed: 1b6c5ae1d23b9d993bc1ca0ab3ce1249b3284a1e. Basically some lines of code are not run when at least one driver is not present.

Upgrade to v0.12.0.AP when it is released.

In the interim, drop any driver, such as the attached, into your `/EFI/BOOT/X64_Drivers` folder if it is empty after running ConfigFactory: [x64_dummy.zip](https://github.com/dakanji/RefindPlus/files/5854480/x64_dummy.zip)

This will not be required as of the next release.

Leaving this closed. Thanks.

**Comment by CornCat78** [comment]
Thank you for your assistance.  Since I cannot remember exactly what options I changed in ConfigFactory to get the non-OC macOS installation seen, would you be able to tell me which conf file I need to look at and compare?  I have a feeling that the latest configuration includes the option of running or installing Windows set to true, whereas previous iterations I had left it at the default selection of false.  I would like to confirm that though.

And just to clarify - the contents of x64_dummy.zip should only be placed in the /X64_Drivers folder if after running ConfigFactory initially or again, no .efi files are present?  

Now that I think about it, comparing latest configuration by dumping the EFI folder, x64_ntfs.efi now exists whereas it was absent before.  See screen shot:
![image](https://user-images.githubusercontent.com/77812799/105482861-00d8bd80-5c77-11eb-8bb4-0a6c343e0829.png)

**Comment by dakanji** [comment]
Just dump the dummy driver there after running if it is empty.

Don't bother doing further comparisons. This is just a temporary workaround till the next release due in about a week.

**Comment by CornCat78** [comment]
Sounds good.  Many thanks again for you generous assistance.  I really appreciate all the hard work you do.  RefindPlus is an excellent application!  Have a nice weekend.

**Comment by steveschow** [comment]
I guess I just experienced the same thing.  My system was working fine and I simply rebooted without changing anything in EFI partition, but when it came back the RefindPlus boot screen was totally blank, didn't even show the OC configs.  see image.

I cleared NVRAM, booted to Mojave and then re-blessed to try again and then it would show the OC icons, but still not the volumes.  

I hope the fix you did will resolve this, will plan on that.. here is my RefindPlus configuration in case you spot anything that might effect it

```
##################################################################
##                BASIC CONFIGURATION SECTION                   ##
##        Config items that **MAY** require amendment           ##
##################################################################

# MENU SCREEN TIMEOUT
# "-1" triggers an immediate automatic boot to the default selection.
# "0" disables automatic booting (i.e., no timeout).
# Other values cause a pause for the value in seconds before booting.
timeout 20

# SCREENSAVER TIMEOUT
# Blanks screen and shows different solid colours after the specified
# number of seconds without input. Screen returns after most keypresses
# (Excluding modifier keys such as Shift, Control, Alt, or Option).
# "-1" causes RefindPlus to start up with the screen saver active.
# The default is 0, which disables the screensaver.
screensaver 0

# Partitions/Volumes that should *NOT* be scanned for bootloaders:
dont_scan_volumes "Legacy OS","Recovery","Boot OS X","PreBoot","VM","Scratch","CCC","CCC - Data","TimeMachine","Data1","Data2"

# Override UI Scaling as follows:
#  -1    - Never scale UI elements up
#   0    - Scale UI elements up, or not, based on screen vertical resolution
#   1    - Always scale UI elements up
#
#scale_ui 0
scale_ui 1


# New feature to force HiDPI mode. - Not sure if this is actually a feature
# this may have been only in experimental build, but anyway where it is.
#force_hidpi true


# MANUAL MENU STANZAS
#
# Default OpenCore Pathway
menuentry "Catalina" {
    icon /EFI/BOOT/overrides/images/macos-catalina.png
    loader /EFI/OC/Bootstrap/Bootstrap.efi
}
# Alternate OpenCore Pathway
menuentry "Catalina - UPDATE" {
    icon /EFI/BOOT/overrides/images/macos-catalina.png
    loader /EFI/OC_ALT/Bootstrap/Bootstrap.efi
}

##################################################################
##              ADVANCED CONFIGURATION SECTION                  ##
##   Config items that typically **DO NOT** require amendment   ##
##################################################################

# Directories that should *NOT* be scanned for bootloaders:
dont_scan_dirs "/EFI/OC","/EFI/OC_ALT","/EFI/OC_DEV","/EFI/OC_WRK","/EFI/x64_drivers","/EFI_BAK"

# Files that should *NOT* be included as bootloaders:
dont_scan_files "+","tmbootpicker.efi","DBG-Bootstrap.efi","Bootstrap.efi","REL-Bootstrap.efi","DBG-OpenCore.efi","OpenCore.efi","REL-OpenCore.efi","BOOTx64-DBG.efi","BOOTx64-REL.efi"

# Tools to include and display order:
#showtools "about","csr_rotate","hidden_tags","shell","clean_nvram","reboot","shutdown"
showtools "about","hidden_tags","shell"

# Additional folders to scan for EFI drivers and scan order:
#scan_driver_dirs "EFI/tools/MyDrivers","OtherDrivers"

# Set arbitrary boot arguments in Mac OS:
#set_mac_boot_args "-v"

# Add UGA Protocol to GOP (true) or not (false):
uga_pass_through true

# Use inbuilt text renderer (true) or not (false):
text_renderer true

# Provide Direct GOP Renderer (true) or not (false):
direct_gop_renderer false

# Force enable TRIM on non-Apple SSDs (true) or not (false):
force_trim true

# Add GOP to the console out handle if required (true) or not (false):
provide_console_gop true

# Disable Mac OS compatibility check when booting (true) or not (false):
disable_mac_compat_check true

# Prevent UEFI Windows from writing to Apple NVRAM (true) or not (false):
protect_mac_nvram true

# Disable Apple Mobile File Integrity (AMFI) checks (true) or not (false):
disable_amfi false

# Store RefindPlus variables in NVRAM (true) or in the "vars" folder (false):
use_nvram false

# Proceed after a delay when warning messages are shown (true) or not (false):
continue_on_warning false

# Prevent UEFI Windows from writing to Apple NVRAM (true) or not (false):
protect_mac_nvram true

# Icon sizes. All icons are square, so just one value is specified:
small_icon_size 36
#big_icon_size 104
big_icon_size 96

# Values for toggling System Integrity Protection (SIP):
csr_values 10,87F

# Name of folder where icons are stored:
icons_dir overrides/images

# Custom title banner:
banner overrides/images/Banner.png

# How to handle banners that are not the same as the screen size:
banner_scale fillscreen

# Custom images for selection backgrounds:
selection_big   overrides/images/Selection_Big.png
selection_small overrides/images/Selection_Small.png

# Font to use for all textual displays in graphics mode:
#font overrides/images/myfont.png
font overrides/fonts/dejavu-sans-mono-bold-24.png

# Types of bootloaders to search for and display order:
scanfor "manual","external","biosexternal","optical","cd","internal","hdbios"

# Boot in Graphics Mode (0) or Text Mode (1):
textonly 0

# Default menu selection:
default_selection 1

#scan_delay 1


#################################################################
##               CUSTOM CONFIGURATION SECTION                  ##
##    Custom configuration items (including custom themes)     ##
#################################################################
#
# Custom configuration tokens go into this section.
# These may be items from the refind.conf file not specified in this file.
#
# Custom theme configuration tokens are typically in a "theme.conf" file.
# Copy and paste the contents of such below to implement custom themes.
# You may need to edit paths.
#
```

debug logs available upon request.

**Comment by dakanji** [comment]
This issue is understood and a temp workaround posted.

Please only add to this if you seem to have the same issue and the workaround is not working or you still expereince the same issue with v0.12.0.AP and newer when released.
