### ISSUE TITLE
Wrong icon for detected kernels

### ISSUE THREAD

**Issue by emperor06** [dakanji/RefindPlus#170]
### RefindPlus Version

v0.14.0.AA Release

### Device Type

UEFI PC

### Problem Description

When scanning for linux kernels, the icon can be set using the filesystem's label or the gpt partition's label.
I don't know if it's a bug or a feature, but the word 'linux' is always appended first to the icon hints:

    Trying to Locate an Icon Based on Hints:- 'linux,deboot,DEBIAN,BOOT'

Because of this, the gpt label is never used and all the kernels have the same `os_linux.png` icon.

### Problem Point

Before starting a loader or tool

### Affected Items

Lin OS Loader

### Debug Log

[23p31j1712.log](https://github.com/dakanji/RefindPlus/files/12484738/23p31j1712.log)

    ***[ Creating Icon Hint From Loader Path:- 'vmlinuz-6.4.0-3-amd64'
    0:781    0:000  Merge Hints Based on Filesystem Name:- 'deboot'
    0:782    0:000  Merge Hints Based on Partition Name:- 'DEBIAN_BOOT'
    0:783    0:000  Trying to Locate an Icon Based on Hints:- 'linux,deboot,DEBIAN,BOOT'
    ***[ Trying to Load Icon from 'themes\minimal\icons' with Base Name:- 'os_linux'
    ***[ In egLoadFile ... Loaded File:- 'themes\minimal\icons\os_linux.png'

**Comment by dakanji** [comment]
Consult the ReadMe on the front page of this repo.

Hint ... go the the [Divergence Section](https://github.com/dakanji/RefindPlus?tab=readme-ov-file#divergence) and read the `Loader Icons` entry.

**Comment by emperor06** [comment]
My apologies, I missed that option. That was the issue. Thanks a lot for the hint.
