### ISSUE TITLE
Issue #163 marked as "For collaborators only" - Can't reply there

### ISSUE THREAD

**Issue by billabongbruno** [dakanji/RefindPlus#171]
### RefindPlus Version

v0.14.0.AB Release

### Device Type

UEFI PC

### Problem Description

              Revisiting this, can you download and try v0.14.0.AB to see if the issue is still present?

_Originally posted by @dakanji in https://github.com/dakanji/RefindPlus/issues/163#issuecomment-1758082401_
            

Hey there, once more.
Issue #163 is marked for collaborators only and I can't reply there, so I'll do it here instead.

So, as per usual, I kept an interest in your repo and as soon as I saw the issue marked as resolved and spotted the Hotfix (x64_RefindPlus_001400-AA_HotFix-01), I gave it a shot as soon as I could and it worked perfectly.

Having tried the new "x64-RefindPlus_001400-AB" version just now, as per your request, I am happy to say that it continues to work flawlessly.

All five OSes I run (Kali, Ubuntu, Windows 11, macOS Sonoma and ChromeOS 118 Beta) are booting without any issues, as well as the functions I have set on my end (Restart, Shutdown and Reboot to Firmware).

The only thing that's different is that with this new version, the entry name under my BIOS shows up as blank (doesn't show anything), as opposed to all previous versions, which showed up as "rEFIndPlus", after I manually set it once.
Not an issue whatsoever for me, just letting you know something changed in that department.

Sorry for the late reply, I had to compare both "config.conf" files extensively to ensure nothing was input wrong on my end, as there were several text changes within the file and a simple "Compare" with Notepad++ wasn't really helping, as almost everything was highlighted.
So I ended up visually comparing both files side by side and just going for the lines that appeared in white (the uncommented ones) as opposed to the green ones (commented ones) (with my dark theme under Notepad++).

But yes, everything is working perfectly and I truly appreciate the work and effort you have put into this project.

Thank you.

Best regards,
Bruno.

### Problem Point

Other

### Affected Items

Other Item

### Debug Log

No log required.

**Comment by billabongbruno** [comment]
Feel free to close this after you read it, as it isn't an issue, it was just a workaround for me to be able to get in touch with you in order to reply.

**Comment by dakanji** [comment]
I see. Thanks.

Strange that you should not be able to reply there since it had been reopened. In any case, better to use the discussions feature instead of opening a new issue. I will convert this.
