### ISSUE TITLE
Use media keys (volume -+) for navigation

### ISSUE THREAD

**Issue by izzylaif** [dakanji/RefindPlus#173]
### Suggested Feature

Consider using standard Volume- and Volume+ buttons for OS selection (i.e. Vol- cycles through available OSs, Vol+ boots the selected)

### Background Information

There is a resurrection of x86-based portable devices with no or limited HID input (handhelds as Lenovo GO, Asus ROG Ally, Steam Deck, GPD Win, Aya Neo and an army of no-name Windows tablets).
While the built-in gamepads, touchpads and touchscreens could be used before OS starts, it usually requires some tinkering.
Those devices have volume rockers, which report as standard Vol-/+ buttons, which could be used as alternative to arrows and enter.

**Comment by dakanji** [comment]
Thank you for the suggestion. 

I can see how this might be useful on such devices but I am afraid I do not intend to look into implementation at this time although submitted code will be considered.

Alternatively, you could try making your request to the upstream rEFInd project and the feature will be added to RefindPlus if implemented upstream.
