### ISSUE TITLE
Display Resolution Issues in VirtualBox

### ISSUE THREAD

**Issue by birdie-github** [dakanji/RefindPlus#175]
### RefindPlus Version

v0.14.0.AC Release

### Device Type

Other Device

### Problem Description

Under VirtualBox with EFI mode enabled, Refind Plus boots into staggering 6400x4800 resolution and I cannot use it because my actual display is only 1440p. That doesn't seem right.

No other EFI enabled boot loader does the same.

### Problem Point

Before starting a loader or tool

### Affected Items

Other Item

### Debug Log

[debug.log.zip](https://github.com/dakanji/RefindPlus/files/14229797/debug.log.zip)

**Comment by birdie-github** [comment]
I've added `resolution 1920 1080` to the config file and it didn't really help.

It still boots into 6400x4800 only it moved the GUI to the left upper corner so at least it's kinda usable.

[debug.log.zip](https://github.com/dakanji/RefindPlus/files/14229811/debug.log.zip)

**Comment by dakanji** [comment]
Consider ditching terms like `insane` and just stick to describing your issue.

The attached log is incomplete ... Please attach a complete log file and use `log_level 1` as want to see a bit more on this one.

Thanks.

**Comment by birdie-github** [comment]
It takes roughly 10 minutes to download and install VirtualBox instead of playing a ping pong game but whatever:

[debug.zip](https://github.com/dakanji/RefindPlus/files/14229922/debug.zip)

**Comment by dakanji** [comment]
I don't see any thing out of the ordinary.

**Comment by birdie-github** [comment]
This is the last time I'm reporting anything to you.

Sorry for the noise.

I get it you don't want bug reports and you don't care.

**Comment by dakanji** [comment]
This would have been looked into but good riddance I suppose

**Comment by birdie-github** [comment]
"Good riddance" is very technical of you. Really appreciated.

This is the first time I'm having such an interesting conversation with a developer and I'm sorry you're going through something rough in your life if you want to discuss anything but the issues being reported.
