### ISSUE TITLE
Shutdown doesn't work under VirtualBox

### ISSUE THREAD

**Issue by birdie-github** [dakanji/RefindPlus#176]
### RefindPlus Version

v0.14.0.AC Release

### Device Type

Other Device

### Problem Description

Choosing shutdown shows a black screen, a single CPU core starts consuming 100% and it freezes there.

### Problem Point

Other

### Affected Items

Other Item

### Debug Log

#175

**Comment by dakanji** [comment]
Please share a log when going through this specific issue.

**Comment by birdie-github** [comment]
The same is in #175 except for the last lines:

```
  0:4282   0:0012  INFO: Clear Keystroke Buffer ... Already Started
                         
  6:2283   5:8000  R U N   S Y S T E M   S H U T D O W N
  6:2301   0:0017  Running System Shutdown
< << <<< * >>> >> >
```

**Comment by birdie-github** [comment]
A waste of time.

**Comment by dakanji** [comment]
This was the one meant to be tagged invalid and not the other.
In any case, didn't appreciate the rude tone anyway.
No sweat since both shut down anyway

**Comment by birdie-github** [comment]
There was **nothing rude** in my initial bug reports.

However you did paid attention to the word "insane" and then proceeded to claim there was no bug report despite the application royally misbehaving to the point of being unusuable, a behavior not found in the original Refind application.

Now you are baselessly accusing me of being "rude" after you made it look like you did not care one bit. I'm glad RefindPlus exists and I'm extremely thankful for your work, but maybe you could simply close this bug tracker if you're not interested in fixing bugs.

**Comment by dakanji** [comment]
As i explained, I wrongly tagged the resolution issue when I meant to tag the shutdown one.
And yes, I do find your tone and choice of wording, a request of a log is playing `ping pong, to be rude

Anyway, you have made your call and let us leave it there.
The several issues addressed here state the opposite of what you claim.

If you prefer the upstream tool, this is a good option to use.
I will look into the resolution issue down the line
Goodbye
