### ISSUE TITLE
Only Generic Linux Icon Displayed

### ISSUE THREAD

**Issue by chevcheli0s** [dakanji/RefindPlus#178]
### RefindPlus Version

v0.14.0.AC Release

### Device Type

UEFI PC

### Problem Description

In Refind there was a Debian logo in the menu list, but in RefindPlus there is always a Linux(tux) logo.

### Problem Point

Before starting a loader or tool

### Affected Items

Lin OS Loader

### Debug Log

[24c12m5413.log](https://github.com/dakanji/RefindPlus/files/14236522/24c12m5413.log)

### Additional Context
<details>
<summary>Screenshots</summary>

![ScreenShot_000](https://github.com/dakanji/RefindPlus/assets/48658076/4b2d4b45-ed81-4a4d-ad48-e02133c46854)
![ScreenShot_001](https://github.com/dakanji/RefindPlus/assets/48658076/2a83a0eb-181e-412e-8380-6bd5994c8a41)

</details>
Also question about "unknown volume", why unknown?

_No response_

**Comment by dakanji** [comment]
Please refer to [Issue 170](https://github.com/dakanji/RefindPlus/issues/170)
