### ISSUE TITLE
Setting timeout to -1 Does Not Work

### ISSUE THREAD

**Issue by SteelT1** [dakanji/RefindPlus#182]
### RefindPlus Version

v0.14.0.AC Release

### Device Type

UEFI PC

### Problem Description

If boot timeout is set to -1 in the config, the default selection won't be booted instantly. RefindPlus would instead load in text mode with the automatic boot timer set to a really high negative number counting up.

### Problem Point

Before starting a loader or tool

### Affected Items

All OS Loaders (First Row Items)

### Debug Log

[24j22y4636.log](https://github.com/dakanji/RefindPlus/files/15409597/24j22y4636.log)

**Comment by dakanji** [comment]
Thanks for the report.
Will look into this and address as required presently.

PS: Please try setting to `1` as a workaround in the interim.
