### ISSUE TITLE
NVRAM Boot Entries Are Shown As Shell Tools

### ISSUE THREAD

**Issue by emperor06** [dakanji/RefindPlus#184]
### RefindPlus Version

v0.14.1.AA Release

### Device Type

UEFI PC

### Problem Description

My tool row is filled with many shell icons, corresponding to the various entries I have in nvram (like local HD, usb, optical, or OS boot entries).
My config contains `showtools shell`

### Problem Point

Before starting a loader or tool

### Affected Items

One or More Tools (Second Row Items)

### Debug Log

Debug logs are on the way, but I've been browsing scan.c and found 2 suspicious things. I don't know if that could help.

First, ScanForTools, case TAG_SHELL always calls ScanFirmwareDefined(), even if a shell has already been found. Maybe that's intended, I don't know,  but I found it strange to search the firmware if we've already found the tool.

Second, in ScanFirmwareDefined(), if DontScanFirmware is empty, then every nvram entries are scanned and added, regardless of MatchThis (which, in this case, should contain L"shell"). I think that's why all the firmware entries become uefi shells in my toolbar.

**Comment by emperor06** [comment]
I've added a dummy `dont_scan_firmware "hello world"` to my config and the wrong shell tools are gone.

Here are the logs.
[24k15s4428.log](https://github.com/user-attachments/files/15848718/24k15s4428.log)

**Comment by dakanji** [comment]
Thanks for the report and input.
That aspect does need a revisit.
Will get to it presently.
