### ISSUE TITLE
v0.12.0.AP broken...

### ISSUE THREAD

**Issue by steveschow** [dakanji/RefindPlus#19]
I upgraded to v0.12.0.AP, left configuration exactly the same except renamed the `force_trim` to `trim_force` per the release notes.  The debug log shows it starting, and then no more logging after that...and I get nothing but a black screen.

**Environment:**
 - RefindPlus Version : v0.12.0.AP
 - Hardware
   * Computer         5,1
   * GPU Model      RX580
   * GPU Port         DVI
   * GPU Flash        NO
 - Affected OS       Catalina

[config+logs.zip](https://github.com/dakanji/RefindPlus/files/5901413/config%2Blogs.zip)

**Comment by dakanji** [comment]
Thanks. Will withdraw the release and review later
