### ISSUE TITLE
RefindPlus Hangs on UGA Graphics

### ISSUE THREAD

**Issue by pauleec** [dakanji/RefindPlus#192]
### RefindPlus Version

v0.14.1.AA Release

### Device Type

Apple Mac

### Problem Description

I've been trying to use the refindplus efi to help the system load Microsoft UEFI 2.0 efi's. I;m very keen to keep the machine being able to load Windows via the UEFI 2.0 support provided by RefindPlus. Every time the machine loads the efi it locks on the "select boot drive" screen. The log generated by the debug efi always shows the same thing.

[24p01x0541.log](https://github.com/user-attachments/files/16455451/24p01x0541.log)

This is consistent on each reboot to the refindplus efi. The machine is able to boot into the standard refind efi but this does not give the Uefi 2.0 support I need. Can you suggest anything I might be able to do to get this really useful and important enhancement working on the imac8,1.

### Problem Point

RefindPlus crashes/hangs on start

### Affected Items

All OS Loaders (First Row Items)

### Debug Log

https://github.com/user-attachments/files/16455451/24p01x0541.log

[24p01x0541.log](https://github.com/user-attachments/files/16464325/24p01x0541.log)

### Additional Context

I am able to use the same test USB boot configuration with the latest refind.efi (v0.14.2). Unfortunately this will not load the MS Windows 10 efi (and I hope eventually Windows 11 efi in an unsupported configuration). The only way I can get windows 10 running on the imac8,1 is using the legacy mbr loader. With Windows 10 reaching its end of life and Windows 11 not supporting legacy mbr bootloaders the only way forward for this machine is to find a way for the MS Windows UEFI 2.0 spec'd efi's to load onto the imac8,1. Duet/Refind-plus will I hope provide this mechanism.

**Comment by dakanji** [comment]
There are a number of overlapping issues and considerations here.

The key/immediate ones are:
1. You wish to use UEFI Windows on your Early 2008 iMac
    - The perceived knowledge is that UEFI Windows cannot be run on Macs of that vintage
    - This is what is widely held to be the case for the Early 2008 Mac Pro at least  
2. You have tried to use rEFInd, and directly presumably, but UEFI Windows failed to load
     - This may have compromised your nvRAM chip
     - A compromised nvRAM chip typically ultimately results in the unit getting bricked
     - The failure to load UEFI Windows may be a validation of the perceived knowledge
     - Note that running UEFI Windows on RefindPlus does not affect the nvRAM due to the `ProtectNVRAM` feature
3. You have tried to use RefindPlus to leverage the `UEFI Support` feature but RefindPlus failed to load
     - There is an bug where RefindPlus hangs with UGA based GPU
     - I had noticed some time ago when I swapped in such a GPU to test something but a fix has been sitting on the back burner

Of these items, Item 3 is what is specific to RefindPlus and what we will do is address this.

Item 2 is potentially critical, and should be urgently dealt with first, but we cannot as you have taken the unfortunate step of having only UEFI Windows installed on your Mac. This means this is what your firmware will try to load by default every time you start your Mac. However, whenever an attempt is made to load UEFI Windows outside RefindPlus (or OpenCore), potentially damaging items will be inserted into your nvRAM.

You would probably need to get macOS reinstalled at some point as a Mac should always have this installed, even if not used, as there are many key actions that require macOS or are best done in macOS.

We can still address Item 3 and, with RefindPlus active, try to mitigate and ultimately walk back from Item 2. 

> [!CAUTION]
> **DO NOT TRY TO CLEAR NVRAM OR `RESET PRAM` ETC!**

So, first stab is to try to following steps:
- Set the `resolution` config token to `resolution 1680 1050`
- Make sure the `timeout` config token is set to `0` to avoid auto boots
- If RefindPlus is loaded after, shut down and do not try to boot UEFI Windows

Report back after for the next steps.

**Comment by pauleec** [comment]
Ok will try the updates you advise and let you know the result.

**Comment by pauleec** [comment]
Okay I made the suggested changes to the config file and have attached the log file generated by the refindplus debug efi file.
[24p06s0247.log](https://github.com/user-attachments/files/16506044/24p06s0247.log). the log file seems to show the .efi is hanging earlier than before.

**Comment by dakanji** [comment]
Do you have access to another Mac?

**Comment by pauleec** [comment]
Okay, I've tried the configuration values you have suggested and the system does seem to get further in the log which I have attached here:
[24p06t1453.log](https://github.com/user-attachments/files/16506788/24p06t1453.log)

I experimented with the resolution flag set to 1024 768 and noted for some reason the value not being picked up by the .efi from the log file it generated which is here: 
[24p06t0657.log](https://github.com/user-attachments/files/16506833/24p06t0657.log)

The log file populates very slowly. Initially I had been rebooting the machine after 30 seconds but noticed the log files being generated were short in length. I leave the machine now for 2 mins each reboot and get a more consistent log file length. I notice that the x64 ntfs driver is also being loaded from the driver directory. I have tried removing the efi but the boot process does not get as far as when the driver is included/loaded (not sure why).

**Comment by pauleec** [comment]
I do have access to another mac but it is at another location so will take me a bit of time to do/get what you need.

**Comment by pauleec** [comment]
out of interest why are the log files a different size each boot? (even when the config.conf is the same)...?

**Comment by dakanji** [comment]
> I leave the machine now for 2 mins each reboot

Try 5 or even 10 Mins to be certain as you are booting from a USB stick and presumably have an HDD in the unit.
USB sticks slow things down and HDD do the same. Having both compounds slowness.

No idea on the log size item.

Share the log after the longer wait.

**Comment by pauleec** [comment]
Irebooted and left the machine for an hour. The log file gets to 11571 in size and stops at the same point as before. Here's the latest log file: 
[24p07m5957.log](https://github.com/user-attachments/files/16517864/24p07m5957.log)

**Comment by pauleec** [comment]
PS I am in Sydney/NSW Australia so apologies for any delay/lag in my response.

**Comment by dakanji** [comment]
Noted on location.

Please try this test build and share the log: https://temp-file-share.web.app/d/G9uE-y3gv
NB: The file is only available for 24 hours.

Thanks

PS: You don't need to wait for a hour etc. 10 mins max is enough.

**Comment by pauleec** [comment]
Ok I have downloaded and booted from the test build. It appears to be stopping at the same point. Here is the log:

[24p07t1755.log](https://github.com/user-attachments/files/16519970/24p07t1755.log)

Is the another level of logging that can be switched on in to help see more precisely where the efi is failing/locking up?

**Comment by dakanji** [comment]
Thanks. Will take a look at the log later.
We will get to more involved logging down the line.
This aspect does not have the required code for such in place.
Need to eliminate some things first to know where to add the flags.

**Comment by dakanji** [comment]
In the interim, can you try rerunning the same file after deactivating the `resolution` config setting?

**Comment by pauleec** [comment]
Sure here's the new log: 
[24p07y0309.log](https://github.com/user-attachments/files/16523092/24p07y0309.log)
It gets to: 

53:9233   0:4080  Determine Graphics Control Method:
                     - Locate Console Control Protocol
                       * Seek on ConOut Handle ... Success
                     - Assess Console Control Protocol ... ok
                   
                     - Locate Universal Graphics Adapter
                       * Seek on ConOut Handle ... Success
                     - Assess Universal Graphics Adapter ... ok
                   
                     - Locate Graphics Output Protocol
                       * Seek on ConOut Handle ... Not Found

**Comment by pauleec** [comment]
I just tried uncommenting the "text mode 2" (which I don't think it liked!) and "textonly" flags... and, after about 60 seconds was able to boot to the text only menu. Unfortunately my current boot drive is configured legacy MBR boot for windows 10. Its will take me a while to setup a fresh boot drive using the GPT UEFI boot on the native drive - so will do some more tests with a USB over the next few days. Its encouraging its got to the text menu though ... here's the log it generated: 
[24p07y4543.log](https://github.com/user-attachments/files/16529100/24p07y4543.log) FYI when it attgempted to boot to the "legacy MBR" the screen went black/blank and a thin white bar reached about 25% along the top of the screen see picture: 
![IMG_0359](https://github.com/user-attachments/assets/fc5f87a0-ab65-4537-870a-65bc673240d5)
The machine did not complete the boot of the MBR and stopped there. FOr me this is less important than trying to get the MS UEFI 2.0 efi loading... I'll see if I can find a way to test that will load okay.

**Comment by dakanji** [comment]
Your unit is at risk of being bricked .... precisely because you have probably tried to load UEFI Windows on it.
RefindPlus SHOULD protect from that particular issue but it SHOULD be addressed before further boot attempts. This is more so with further UEFI Windows boots.

Anyway, I think I need to sort the UGA issue out on my unit.

What you need to look into is:
1. Go to this link and use the script file to create a macOS El Capitan USB installer
    - https://gist.github.com/dakanji/1ab88389c7aaffe4b156db9741687b3a
    - Instructions are at the top of the script file
    - You will need another Mac
2. Optionally but preferrably, open the unit up and change the HDD inside to SSD 
    - https://eshop.macsales.com/shop/ssd/owc/imac/2008
    - There is a video guide there
    - For reference, my 2008 Mac loads RefindPlus in 3 to 5 seconds
3. You need to then use the USB installer created in Item 1 to install El Capitan on the unit
    - That is, get rid of the current Windows setup 
    - The nvRAM can be then checked and mitigated BEFORE finally looking into getting Windows up.
    - The `Firmware Features` indicating whether UEFI Windows is supported needs to be checked from macOS btw

Anyway, the other issues around the subject away from the UGA fix are not RefindPlus specific and can be picked up back on the discussion thread you created where you can either be walked through or you might want to take things somewhere like the MacRumors forum: https://forums.macrumors.com/forums/early-intel-macs.230.

You can @mention me there. User name is `Dayo`

I will look into the UGA issue on my unit and update this Issue Item when done.
In the meantime, this will be closed and locked down.

Good luck
