### ISSUE TITLE
Cannot Boot Debug Version

### ISSUE THREAD

**Issue by MarioG-X** [dakanji/RefindPlus#193]
### RefindPlus Version

v0.14.2.AA Release

### Device Type

Apple Mac

### Problem Description

The debug version of 14.2 results in the computer booting to a circle/crossed on an iMac 2012. I powered down, etc. nothing works. I can boot to the non-debug version but it has an issue that required a log file which is why I needed debug: The RP 14.2.AA standard version does not display Linux partitions (macOS OK) and I will open an issue once I get logs. I have follow_symlinks uncommented/copied from previous config.

### Problem Point

RefindPlus debug version crashes/hangs on start, or is not bootable to iMac

### Affected Items

Other Item

### Debug Log

None, the is the problem.

### Additional Context

Will hold up testing on the 2018 Mini until this is resolved.

**Comment by dakanji** [comment]
I have no issues booting Linux, Windows and Mac OS on my unit.
I'll suggest you check whether things work on another unit.

**Comment by MarioG-X** [comment]
Ok I did it on the 2018 Mac mini but don't know how that will help since RP debug is broken, except I did get a message not on the iMac. First,  the OpenSUSE systems still don't show up using non-debug. Second, when trying the debug version I got a message about "invalid while getting loaded image protocol handle", a red line at the top. So same failures on iMac and Mac Mini. the debug version is badly broken.

**Comment by dakanji** [comment]
> I got a message about "invalid while getting loaded image protocol handle"

Well, that is an important piece of information missing from your initial report which gave nothing to work with.
Please check the message again and confirm whether it was "While Getting a LoadedImageProtocol Handle" or "while Getting LoadedImageProtocol Handle". That is does it include `a`?

**Comment by MarioG-X** [comment]
> Well, that is an important piece of information missing from your initial report which gave nothing to work with. 

That's because the iMac gave nothing at all, Don't know what you could do if I did not have a second Mac mini to test on that showed the message below. Good thing the Mini is available and showed a difference.

>Please check the message again and confirm whether it was "While Getting a LoadedImageProtocol Handle" or "while Getting LoadedImageProtocol Handle". That is does it include `a`?

The message is in red reverse video centered at the top of the screen, exact text is:

Error: 'Invalid Parameter' while Getting LoadedImageProtocol Handle

**Comment by dakanji** [comment]
Thanks.

> Don't know what you could do if I did not have a second Mac mini to test

Would have tagged this as `"Cannot Replicate"` and closed it down until more information is available.
Anyway, please test the linked build: https://file.io/KKAbUb0OAtF1

**Comment by MarioG-X** [comment]
That fixed it on both computers. You may close if you are done with this issue. I have 2 logs for the missing Linux's I will open that issue as soon as I type it up in a few minutes.

**Comment by dakanji** [comment]
There is one more test needed but I will see if I can do it myself first.
Will get back if not (best on Linux).

**Comment by MarioG-X** [comment]
As mentioned power is out all day, new pole. If you need something I will be glad to do it after power comes back. Running on batteries for Wi-Fi until they run out in a few minutes.
