### ISSUE TITLE
v0.12.0.AP not showing volumes without dummy driver

### ISSUE THREAD

**Issue by steveschow** [dakanji/RefindPlus#20]
Using the latest version of RefindPlus that you posted today with the fix for previous issue.  However, this version does not display the non-OC volumes in the boot picker unless I use the dummy driver trick.  I thought that was supposedly going to be fixed in this AP release, but anyway, just letting you know its not.

Also, after using the dummy driver trick, I see two volumes, one of which I was keeping hidden using rEFInd hide volume command (select Volume and press backspace).  This does not hide the volume though and the fact that it confirms with a name "??" must mean its confused by something.  This was working previously in version AN.  

Also, after attempting to hide the one volume, and it didn't work, it also came back to the main boot menu with all the icons shrunken to a smaller size and not displaying the icons correctly.  (see images)

![IMG_0176](https://user-images.githubusercontent.com/9116800/106685546-d4317980-6585-11eb-83b0-f3ab5a23a6bc.jpg)
![IMG_0175](https://user-images.githubusercontent.com/9116800/106685061-de9f4380-6584-11eb-85d1-aa2e4248d247.jpg)
![IMG_0174](https://user-images.githubusercontent.com/9116800/106685052-db0bbc80-6584-11eb-9d3e-8c724ceb6185.jpg)

**Environment:**
 - RefindPlus Version : 0.12.0.AP
 - Hardware
   * Computer        5,1
   * GPU Model     RX580
   * GPU Port         DVI
   * GPU Flash        NO
 - Affected OS       Catalina

[config+log.zip](https://github.com/dakanji/RefindPlus/files/5915471/config%2Blog.zip)

**Additional context**

**Comment by dakanji** [comment]
Please attach the log when the dummy driver is not present.

**Comment by steveschow** [comment]
sorry, here is new log without the dummy driver:

[21d03b3221.log](https://github.com/dakanji/RefindPlus/files/5915709/21d03b3221.log)


![IMG_0178](https://user-images.githubusercontent.com/9116800/106689916-0a72f700-658e-11eb-9ac2-f45ca233fbef.jpg)

**Comment by dakanji** [comment]
Try the attached and share the log.
It fixes the driver requirement and tries for the hidden tags (resolves the question marks but not yet sure whether other items are fixed at the same time)

[X092-BOOTx64.zip](https://github.com/dakanji/RefindPlus/files/5915762/X092-BOOTx64.zip)

**Comment by steveschow** [comment]
the dummy driver is not needed now, the volumes show up, however, the Hide feature still doesn't work.  It displays a more correct name, but when coming back to the main boot menu after that, the volume is still showing, and the icons are shrunk. and also after I went into the hidden tags sub-item to see if anything was there, it says there are no hidden tags, but when it comes back after that to the main boot menu, not only are the icons smaller, but they are overlapping each other.

attached latest log in case it helps.
[21d03b5829.log](https://github.com/dakanji/RefindPlus/files/5915801/21d03b5829.log)

**Comment by dakanji** [comment]
Try the attached.

[X093-BOOTx64.zip](https://github.com/dakanji/RefindPlus/files/5915917/X093-BOOTx64.zip)

**Comment by steveschow** [comment]
same result

[21d03c3713.log](https://github.com/dakanji/RefindPlus/files/5915963/21d03c3713.log)

**Comment by dakanji** [comment]
OK. Need to dig deeper into potential causes.

**Comment by steveschow** [comment]
just confirming, Version AQ seems to fix all the issues mentioned in this ticket.
