### ISSUE TITLE
OpenCore Hangs When Chainloaded From RefindPlus

### ISSUE THREAD

**Issue by startergo** [dakanji/RefindPlus#26]
**Describe the bug**
A Memory leak was introduced in upstream rEFInd 0.13.1. As a result rEFInd does not load on cMP5,1 and RP cannot chainload OC

**To Reproduce**
Steps to reproduce the behaviour:
Run rEFInd 0.13.1 on cMP5,1 (you may need to use a UGA card with a boot screen) or RP version 0.13.1.AC with the same UGA card with the boot screen.

**Expected behaviour**

**Environment:**
 - RefindPlus Version : v0.13.1.AC (Pre-Release)
 - Hardware
   * Computer         :  MacPro 5,1
   * GPU Model        : RX 580, GT-640 MVC bios
   * GPU Port         : DVI-D and DVI-I on GT-640
   * GPU Flash        : YES-MacVidCards GT-640
 - Affected OS        : OC chainloading

**Log and Config Files**
[21f07e2749.log.zip](https://github.com/dakanji/RefindPlus/files/6097156/21f07e2749.log.zip)
[config.conf.zip](https://github.com/dakanji/RefindPlus/files/6097157/config.conf.zip)

**Comment by startergo** [comment]
I have to say I tested the version bda56bf8a6fc3eb60f32b17af3dd3089a7, and back RefindPlus_x64-001200_AQ, ant they don't chainload:
[opencore-2021-03-07-165352.txt](https://github.com/dakanji/RefindPlus/files/6097560/opencore-2021-03-07-165352.txt)

**Comment by dakanji** [comment]
Tag: https://github.com/acidanthera/bugtracker/issues/1542

That muddies the waters.
Have to find a working version, if any
Can you go back through the versions until you find one that works?
https://github.com/dakanji/RefindPlus/releases

Also need to eliminate any stuff in place that might be messing things up including using a non-MVC flashed card if possible.
 
On the OC side, suggest removing all drivers apart from OpenRuntime.
For RP, there is no need to update config.

**Comment by startergo** [comment]
> using a non-MVC flashed card

With a GOP card there is no issue. As far as the vbios is concerned it is a standard Mac MXM Nvidia efi :
```
Mac_Nvidia GOP 3730 [Feb  4 2013]_MXM
```

**Comment by startergo** [comment]
there is something else which I found while testing rEFInd snapshots. I started testing them to see where the offending commit was and when I reached the "working" commit 0.13.0 and compiled it with EDKv2018 it hung...
So then I compiled it in linux with EDKv2018 and it hung again. Lastly I compiled it with GNU-efi and it worked.

**Comment by dakanji** [comment]
Worth raising there.

**Comment by startergo** [comment]
I will, but first I want to find the broken commit. Now I have to redo all tests with gnu-efi. Can RP be compiled with gnu-efi?

**Comment by startergo** [comment]
Found the broken code:
https://sourceforge.net/p/refind/discussion/general/thread/a5d969d1b6/#ff5f

**Comment by startergo** [comment]
The issue actually is the logging:
```
log_level 3
```
Commented out the logging and now all is booting and chainloading. The chainloading hang must be specific to RP.

**Comment by dakanji** [comment]
> Can RP be compiled with gnu-efi?

Never tried. Most likely not.

> The chainloading hang must be specific to RP.

Possibly. Need to find the last working version as I believe you have mentioned before that it was working until recently.
No need to go commit by commit, just by testing the versions. Although a bit confused by report that v0.12.0.AQ fails if previous position was that this is something recent.

**Comment by startergo** [comment]
rEFInd is booting, logging and chain loading now with ```use_nvram false``` in the latest commit:
https://sourceforge.net/p/refind/discussion/general/thread/a5d969d1b6/#7a37

**Comment by dakanji** [comment]
Interesting on rEFInd but actually still waiting for a response to this: https://github.com/dakanji/RefindPlus/issues/26#issuecomment-792319822

**Comment by dakanji** [comment]
@startergo ... shutting this down as an upstream issue (closest tag I can put). 

Also tagging as a 'Duplicate' as more or less aware of the base issue (although not specifically a numbered issue) 
Basically, this is just a symptom of a wider issue with memory management. 

I will start to tackle some of these but some are all the way in EDK II itself which is a problem with using an old version.

**Comment by startergo** [comment]
Why do you think it is an upstream issue? If logging is disabled rEFInd chainloads. And RP does not use the same logging as rEFInd anyway.

**Comment by dakanji** [comment]
As said, all you see are symptoms of a real issue which is to do with memory management.
Logging items are just a manifestation of this and with a small amendment of the code, it will manifest elsewhere.
