### ISSUE TITLE
Out-of-bounds access (OVERRUN) in filesystems/fsw_hfs.c >> fsw_hfs_volume_mount

### ISSUE THREAD

**Issue by dakanji** [dakanji/RefindPlus#33]
### Memory Corruption from Out-of-Bounds Access

kHFSMaxVolumeNameChars is set to 27 in
https://github.com/dakanji/RefindPlus/blob/c9e64c9428d555ebbd9640711ebc3c6d56c67b96/filesystems/hfs_format.h#L169

Assigning: s.len = kHFSMaxVolumeNameChars (That is, 27) in:
https://github.com/dakanji/RefindPlus/blob/c9e64c9428d555ebbd9640711ebc3c6d56c67b96/filesystems/fsw_hfs.c#L331

Assigning: s.data = "HFS+ volume". 
s.data now points to byte 0 of "HFS+ volume" (which consists of 12 bytes) in:
https://github.com/dakanji/RefindPlus/blob/c9e64c9428d555ebbd9640711ebc3c6d56c67b96/filesystems/fsw_hfs.c#L332

Overrunning buffer pointed to by s.data of 12 bytes by passing it to a function which accesses it at byte offset 26 using argument s.len (which evaluates to 27) in:
https://github.com/dakanji/RefindPlus/blob/c9e64c9428d555ebbd9640711ebc3c6d56c67b96/filesystems/fsw_hfs.c#L333

**Comment by joevt** [comment]
size and len should be 11.

Change line 331 and 332 to this:
```
        #define kHFSVolumeNameFallback = "HFS+ volume";
        s.size = s.len = (sizeof(kHFSVolumeNameFallback) - 1);
        s.data = kHFSVolumeNameFallback;
```

**Comment by dakanji** [comment]
Thanks. That should fix it
