### ISSUE TITLE
Out-of-bounds access (OVERRUN) in filesystems/fsw_ext4.c >> fsw_ext4_readlink

### ISSUE THREAD

**Issue by dakanji** [dakanji/RefindPlus#34]
### Memory Corruption from Out-of-Bounds Access

Checking dno->g.size > 4096ULL (implies that `dno->g.size` may be up to 4096 on the false branch) in:
https://github.com/dakanji/RefindPlus/blob/c9e64c9428d555ebbd9640711ebc3c6d56c67b96/filesystems/fsw_ext4.c#L726

Assigning: s.len = (int)dno->g.size (The value of s.len may now be up to 4096) in:
https://github.com/dakanji/RefindPlus/blob/c9e64c9428d555ebbd9640711ebc3c6d56c67b96/filesystems/fsw_ext4.c#L735

Assigning: s.data = dno->raw->i_block. 
s.data now points to byte 0 of dno->raw->i_block (which consists of 60 bytes) in:
https://github.com/dakanji/RefindPlus/blob/c9e64c9428d555ebbd9640711ebc3c6d56c67b96/filesystems/fsw_ext4.c#L736

Overrunning buffer pointed to by s.data of 60 bytes by passing it to a function which accesses it at byte offset 4095 using argument s.len (which evaluates to 4096) in:
https://github.com/dakanji/RefindPlus/blob/c9e64c9428d555ebbd9640711ebc3c6d56c67b96/filesystems/fsw_ext4.c#L737

**Comment by joevt** [comment]
I guess there needs to be a check to make sure the symlink size is not greater than 60 bytes when it is inlined.

So after this line:
https://github.com/dakanji/RefindPlus/blob/111e798faa08de9df549300bfb0171f6870988d8/filesystems/fsw_ext4.c#L732

Add this:
```
    if (dno->g.size > sizeof(dno->raw->i_block))
        return FSW_VOLUME_CORRUPTED;
```

**Comment by dakanji** [comment]
Makes sense
