### ISSUE TITLE
Use Refind Plus in MultiBoot Environment

### ISSUE THREAD

**Issue by Tobix99** [dakanji/RefindPlus#4]
Hey, 
so I've installed 3 Operating Systems on my Intel Nuc: Windows, Ubuntu and MacOS X. At first I had Ubuntu and Windows with Grub, but decided to switch to Refind, when using the MacOS. So yesterday I installed MaOS on an APFS Partiton (that's why the switch away from Grub2). Then Via Ubuntu I installed the Piano Core version of  Refind and Booted rebooted. Everything works fine, except I can't Boot MacOS (Windows and Ubuntu worked find). I installed Refind Plus and hoped it can fix it.

I thought I can use this out of the Box an can select on Bootup MacOS, but thats not the case.

Now the interesting part: When I add the OpenCore boot loader, Refind Plus found it and I can "boot chain" to the next boot loader. From there I could start Windows and MacOS (not Ubuntu) or "restart" Refind Plus again. When I do this, now I've the Option to Boot MacOS directly from Refind. Is there maybe a driver missing which OpenCore loads? 

I just want to boot into Refind Plus and from there directly start MacOS/Windows/Ubuntu.

**Comment by dakanji** [comment]
Please refer to the rEFInd Documentation for information on what drivers you need for your Hack to find Mac OS bootloaders
