### ISSUE TITLE
OpenCore skips OpenCanopy when chain loaded from RefindPlus

### ISSUE THREAD

**Issue by startergo** [dakanji/RefindPlus#41]
**Describe the bug**
When chain loading OC a message appears:
RefindPlus - Loading OS (in text mode)
OC boot screen is completely skipped and I can see the verbose text after the timeout selects the default boot option.
**To Reproduce**
Chainload OC through RefindPlus v0.13.2.AA (Pre-Release) on Apple Firmware

**Expected behaviour**
Expected to boot to Open Canopy bootpicker.

**Environment:**
 - RefindPlus Version :  v0.13.2.AA
 - Hardware
   * Computer         :  MacPro 5,1
   * GPU Model        :GTX Titan
   * GPU Port         : HDMI
   * GPU Flash        : YES-MacVidCards 
 - Affected OS        : OpenCore bootpicker

**Log and Config Files**
[21f28u5900.log.zip](https://github.com/dakanji/RefindPlus/files/6217903/21f28u5900.log.zip)
[config.conf.zip](https://github.com/dakanji/RefindPlus/files/6217908/config.conf.zip)

**Comment by dakanji** [comment]
Changed the title to reflect which tool does the skipping.
This needs to be referred to the OpenCore project. 
Can implement any findings that are pertinent here.

**Comment by startergo** [comment]
This is the OC log:
```
00:000 00:000 OCC: No compatible mode for 0x0@0 (max: 1) resolution
00:015 00:015 OC: Changed resolution to 0x0@0 (max: 1, force: 0) from Max - Not Found
00:131 00:116 OCUI: Failed to load images
00:157 00:025 OC: External interface failure, fallback to builtin - Unsupported
10:348 10:190 AAPL: #[EB|LOG:INIT] 2021-03-28T19:56:23
10:363 00:015 AAPL: #[EB|VERSION] <"boot.efi 495.80.3~11 (Official), built 2020-12-21T21:10:06-0800">
10:393 00:029 AAPL: #[EB|BUILD] <"BUILD-INFO[298]:{"DisplayName":"boot.efi","DisplayVersion":"495.80.3~11","RecordUuid":"0B2238C1-809C-49D2-B102-CD53614FF265","BuildTime":"2020-12-21T21:10:06-0800","ProjectName":"efiboot","ProductName":"boot.efi","SourceVersion":"495.80.3","BuildVersion":"11","BuildConfiguration":"Release","BuildType":"Official"}">
```

**Comment by dakanji** [comment]
Thanks.

Please raise an issue on the OpenCore bug tracker with the full log for Vit to have a look.

**Comment by startergo** [comment]
You know what is strange? I thought I pasted/merged the EFI debug folder and as you can see it didn't take it. Instead it was still the release version of boot.efi
Now that I manually copied over the debug files this error is not detected?
```
23:934 22:589 OC: Connecting drivers done...
23:944 00:009 OCC: Found 3 handles with GOP draw
23:963 00:019 OCC: Found 1 handles with Apple Framebuffer info
23:990 00:026 OCC: AppleFramebufferInfo - Got Base 98020000, Size 8847360, RowBytes 8192, Width 1920, Height 1080, Depth 32
24:015 00:025 OCC: Found 4 handles with UGA for GOP check
24:038 00:022 OCC: Trying handle 0 - 75D33198
24:057 00:018 OCC: Skipping GOP proxying as it is already present on handle 0 - 75D33198
24:080 00:023 OCC: Trying handle 1 - 75A11C18
24:102 00:022 OCC: Skipping GOP proxying as it is already present on handle 1 - 75A11C18
24:123 00:020 OCC: Trying handle 2 - 75D64318
24:143 00:020 OCC: Skipping GOP proxying as it is already present on handle 2 - 75D64318
24:169 00:025 OCC: Trying handle 3 - 759EA198
24:189 00:020 OCC: Skipping GOP proxying as it is already present on handle 3 - 759EA198
24:210 00:020 OCC: GOP exists on ConsoleOutHandle and has 1 modes
24:229 00:018 OC: Requested resolution is 0x0@0 (max: 1, force: 0) from Max
24:248 00:019 OCC: Requesting 0x0@0 (max: 1) resolution, curr 65535, total 1
24:265 00:017 OCC: Current FB at 0x0 (0x0), format 3, res 1920x1080 scan 2048
24:289 00:023 OCC: Mode 0 failure - Not started
24:307 00:018 OCC: No compatible mode for 0x0@0 (max: 1) resolution
24:331 00:024 OC: Changed resolution to 0x0@0 (max: 1, force: 0) from Max - Not Found
24:352 00:020 OCC: Found 4 handles with UGA draw
24:370 00:017 OCC: Found 3 handles with GOP for UGA check
24:387 00:017 OCC: Trying handle 0 - 75D64318
24:406 00:019 OCC: Skipping UGA proxying as it is already present on handle 0 - 75D64318
24:425 00:018 OCC: Trying handle 1 - 759EA198
24:443 00:018 OCC: Skipping UGA proxying as it is already present on handle 1 - 759EA198
24:461 00:018 OCC: Trying handle 2 - 75A11C18
24:478 00:016 OCC: Skipping UGA proxying as it is already present on handle 2 - 75A11C18
24:495 00:016 OCC: Using builtin text renderer with 1 scale
24:514 00:019 OCC: Install console control (6E88B458/0/0), current - Success
24:530 00:015 OCC: Setup ASCII Output - Success
24:549 00:019 OC: Requested console mode is 0x0 (max: 0) from 
24:567 00:018 OC: Requested not to use audio
24:584 00:016 OC: OcMiscLoadSystemReport...
```

[opencore-2021-03-28-200457.txt](https://github.com/dakanji/RefindPlus/files/6217981/opencore-2021-03-28-200457.txt)

**Comment by dakanji** [comment]
Best to refer to the OpenCore team for insight.
Might want to add OpenCore config as well

**Comment by dakanji** [comment]
To summarise findings from coordination with OpenCore
- Issue appears to be RP related
- issue appears to be linked to `EFI VBios` flashed cards

Few items before we start trying to track the issue down:
- Please share the RP log from the other failing tested card(s)
- Are those cards all MVC cards?

**Comment by startergo** [comment]
[Archive.zip](https://github.com/dakanji/RefindPlus/files/6223382/Archive.zip)
Logs with GT-640 MVC EFI vbios.

**Comment by dakanji** [comment]
OK. Got that Baseline.

Can you build on the current state of the code base and let's see what gives?

**Comment by startergo** [comment]
With ```text_renderer``` switch ```ON``` it works with the "workaround" version from @vit9696
[Archive 2.zip](https://github.com/dakanji/RefindPlus/files/6224400/Archive.2.zip)

**Comment by startergo** [comment]
It works also with 
https://github.com/acidanthera/OpenCorePkg/commit/dbc9a3de63d224dd9c34ac97fc6ab2e71cf895b7
with ```text_renderer``` switch ```ON```.
[Archive.zip](https://github.com/dakanji/RefindPlus/files/6224433/Archive.zip)

**Comment by dakanji** [comment]
Cool. Try X112. The `text_renderer` setting should not made a difference.

[X112-BOOTx64.efi.zip](https://github.com/dakanji/RefindPlus/files/6224481/X112-BOOTx64.efi.zip)

**Comment by startergo** [comment]
It works as designed now
[Archive.zip](https://github.com/dakanji/RefindPlus/files/6224586/Archive.zip)
