### ISSUE TITLE
Hidden Items feature is not working

### ISSUE THREAD

**Issue by billabongbruno** [dakanji/RefindPlus#47]
Greetings.
So, I have an (originally Windows) laptop that I've been trying to install rEFInd Plus onto.
I have successfully made it to the point where all my custom entries are shown, but I am unable to delete the auto-filled entries.

It throws an error and then pauses rEFInd Plus and I cannot delete any of those entries.

On a side note, I am also unable to theme it using themes that work flawlessly with the "main" version of rEFInd.

I have deleted all drivers from the "drivers_x64" folder.
Is there something I'm doing wrong or missing?

I am using config.conf and not refind.conf as per recommendation.

**Comment by billabongbruno** [comment]
EDIT:
Fixed the issues stated above by forcing rEFInd Plus to scan only External volumes, thus not reading whatever OSes I have on my SSD.

**Comment by dakanji** [comment]
Hello, Just actually read the issue in detail.

Can you give some more information about this as it might be a bug?
>  I am unable to delete the auto-filled entries

Please attach a debug log

**Comment by billabongbruno** [comment]
Hey there.

Sorry, I just got off work now, I hadn't seen your message.

I will be more than happy to help.
How can I provide the debug log in order for me to send it to you?

Also, for some reason I am also unable to load any of my Linux distros with the config.conf I sent you (using the manual boot stanzas pointing to initrd and vmlinuz).

They work just fine with rEFInd's "main" version.

I didn't want to open up another issue on Github, it felt rude of me, as if I were complaining.

That said, how can I provide the log?


________________________________

**Comment by dakanji** [comment]
This particular issue has been fixed now been fixed. Actually better to open another issue on the failure to load item.

You can generate a debug log by running the debug version efi file.

**Comment by billabongbruno** [comment]
> 
> 
> This particular issue has now been fixed. Actually better to open another issue on the failure to load item.
> 
> You can generate a debug log by running the debug version efi file.

Will do so right away.

I once again thank you for all your help.

**Comment by billabongbruno** [comment]
> This particular issue has now been fixed. Actually better to open another issue on the failure to load item.
> 
> You can generate a debug log by running the debug version efi file.

Thank you once again for you help.

I have now opened a new issue with all the info I could provide regarding the issue I came across.
It's probably my mistake again, but it's there regardless.

Thank you again for all your hard work.

Best regards,

**Comment by dakanji** [comment]
I'll have a look.

Btw, thanks for the reports as since I don't use all the available functionality and there isn't a test suite, there is no way of knowing about issues unless reported.

**Comment by billabongbruno** [comment]
You're welcome.
I'm happy to help.

I appreciate the effort you put into the project.
I am very much a tinkerer and like to try most of (if not all) features, as I heavily customize things, as I'm sure you've noticed by now.


________________________________
