### ISSUE TITLE
OpenCore not working with use_graphics_for

### ISSUE THREAD

**Issue by billabongbruno** [dakanji/RefindPlus#48]
**Describe the Bug:**
When loading OpenCore via RefindPlus, the only bootloader that still shows "RefindPlus Using load options (...)" is OpenCore, even though use_graphics_for is enabled and opencore is there as well.

**To Reproduce:**
1. Boot up RefindPlus
2. Choose my manually entered MacOS entry (pointing to OpenCore.efi)
3. Shows (RefindPlus - Starting OpenCore.efi - Using load options ' ')

**Expected Behaviour:**
After choosing the manually added entry to MacOS poiting to OpenCore.efi, the expected behaviour was for the (RefindPlus - Starting OpenCore.efi - Using load options ' ') not to show.

**Environment:**
 - RefindPlus Version : [v0.13.2.AD]
 - Hardware
   * Computer         : [ACER Nitro 5 AN-515-52]
   * Motherboard      : [ACER]
 - Affected OS        : [OpenCore --› MacOS]

**Additional Context:**
Running the latest OpenCore (0.6.9) and the latest OCBinaryData.

**Comment by dakanji** [comment]
Please always follow the issue template when raising an issue.
Kindly edit accordingly.

NB: The tool is called "RefindPlus".

**Comment by billabongbruno** [comment]
> Please always follow the issue template when raising an issue.
> Kindly edit accordingly.
> 
> NB: The tool is called "RefindPlus".

Thank you for your remark, dev.

I have now edited my issue to match the requirements.
Apologies.

**Comment by dakanji** [comment]
Please attach your config.conf file.

**Comment by billabongbruno** [comment]
> Please attach your config.conf file.

Dear dev,

Thank you for your kind and prompt response.

Attached is the config.conf file within a .zip file, so GitHub would accept it.

Best regards,

[Bruno_config.zip](https://github.com/dakanji/RefindPlus/files/6500562/Bruno_config.zip)

**Comment by dakanji** [comment]
- Remove `ostype   MacOS` from the OpenCore manual stanza as OpenCore is not Mac OS
- You can add a `graphics on` line to the stanza although not needed since opencore is in `use_graphics_for`
- Not directly related but better to move your included themes/refind-black/theme.conf before the manual stanzas.
    - That is, replace `#include manual.conf` with this line

**Comment by billabongbruno** [comment]
> * Remove `ostype   MacOS` from the OpenCore manual stanza as OpenCore is not Mac OS
> * You can add a `graphics on` line to the stanza although not needed since opencore is in `use_graphics_for`
> * Not directly related but better to move your included themes/refind-black/theme.conf before the manual stanzas.
>   
>   * That is, replace `#include manual.conf` with this line

Duely noted.
Will try your suggestions ASAP and report back.

**Comment by billabongbruno** [comment]
> * Remove `ostype   MacOS` from the OpenCore manual stanza as OpenCore is not Mac OS
> * You can add a `graphics on` line to the stanza although not needed since opencore is in `use_graphics_for`
> * Not directly related but better to move your included themes/refind-black/theme.conf before the manual stanzas.
>   
>   * That is, replace `#include manual.conf` with this line

Applied your suggestions and everything was fixed.

I really appreciate both your hard work and your prompt help.

Thank you for helping me figure this out.

This issue (which was not an issue with RefindPlus itself, but rather my mistake) is now closed.

Thank you, kind dev.

Best regards,
Bruno.
