### ISSUE TITLE
Not recognizing my 4k monitor as HiDpi

### ISSUE THREAD

**Issue by steveschow** [dakanji/RefindPlus#5]
I am trying to use RefindPlus.  I have been using MyBootMgr to create the initial configuration of RefindPlus and OpenCore.

Unfortunately RefindPlus is not recognizing my monitor as HiDPI, so everything is really small at native 4k resolution.  

I get the following debug messages with RefindPlus in DEBUG mode:

```
15:582   0:057  Set Screen Resolution:
 15:671   0:088    - BestMode: GOP Mode[0] @ 3840x2160
 18:281   2:610    - Switch to GOP Mode[0] ...Success
 18:312   0:030  Screen Resolution Set

 18:342   0:029  INFO: Implemented Graphics Output Protocol

 18:390   0:048  INFO: Implement Text Renderer ...Success

 18:420   0:029  Setup Screen...
 18:450   0:029  Prepare for Graphics Mode Switch:
 18:478   0:028    - HiDPI Not Detected ...Maintain Icon Scale
```

So it appears to recognize correctly the 4k resolution of my GPU (RX580) and monitor, but then it goes on to ignore HiDPI scaling later on.  This is on a MacPro 5,1, with Sapphire Pulse RX580 GPU.

Is this a bug in RefindPlus or something I can configure somehow to work properly?

**Comment by dakanji** [comment]
Please refer to the upstream rEFInd project as from changes made for RefindPlus.

**Comment by dakanji** [comment]
Took a closer look at the code and the issue is a RefindPlus issue.
Will resolve presently
