### ISSUE TITLE
Ability to load ChromeOS kernels directly - like GRUB does

### ISSUE THREAD

**Issue by billabongbruno** [dakanji/RefindPlus#50]
It is NOT related to a problem.

**Describe the solution you would like**

It would be amazing if there were any way for RefindPlus to be able to load a ChromeOS kernel the same way GRUB does.
As it stands, to boot ChromeOS install in a multi-boot environment, GRUB needs to be chainloaded in order for it to work, thus requiring either a Linux Distro installed or Grub2Win or something like that, as I am yet to find a true standalone GRUB install to the EFI folder in the ESP partition.

**Describe alternatives you have considered**

My only approach to this was trying (with no success) to force grubx64.efi to load a grub.cfg file stored locally, but it failed to load those settings everytime.

Would be great to eliminate the process of having to use a Linux Distro to store our grub.cfg in its boot partition in order for ChromeOS to boot.

This way, we would be able to format and do whatever changes needed to our Linux Distro partition or even eliminate it entirely, if needed, without ever affecting our ability to boot into ChromeOS.

**Additional context**

All my testing have been done using the latest Brunch framework and using the multi_install.sh.
That way, ChromeOS gets installed to a single partition on my NVMe rather than partitioning it whole and creating 12 partitions by itself.
What it does is basically create a .img file in the single partition I set during install.

**Comment by dakanji** [comment]
GitHub's "issues" are made up of Bug Reports and Feature Requests, such as this. So it is in the right place. 
There is also a "[Discussion](https://github.com/dakanji/RefindPlus/discussions)" facility if just wanting to mull over something or ask a question.

Moving on the the request, it looks more like something to raise with the maintainers of that OS or perhaps with the rEFInd project for consideration. Unless of course someone is willing to code it up and submit a pull request. Even so, I will most likely suggest they send it upstream instead.

**Comment by dakanji** [comment]
Background on directly booting ChromeOS: [sourceforge.net/p/refind/discussion/general/thread/c91b84cfd7/#acc1](https://sourceforge.net/p/refind/discussion/general/thread/c91b84cfd7/#acc1).

Seems best current option is to use a [thrid party loader such as Grub2Win](https://github.com/dakanji/RefindPlus/discussions/172#discussioncomment-7519606)
