### ISSUE TITLE
What's the function of【RefindPlus_x64-DBG.efi】?

### ISSUE THREAD

**Issue by 1457384613gh** [dakanji/RefindPlus#59]
What's the function of【RefindPlus_x64-DBG.efi】?
How is【RefindPlus_x64-DBG.efi】different from 【RefindPlus_x64-REL.efi】？
【RefindPlus_x64-REL.efi】is to be renamed【RefindPlus_x64.efi】and put into ESP: /EFI/refindplus/ ,
but
is【RefindPlus_x64-DBG】to be renamed【BOOTX64.EFI】and put into ESP: /EFI/BOOT/ ?

**Comment by dakanji** [comment]
You have already asked this question in the correct place, which is the Q&A section.
Please do not duplicate such items.
