### ISSUE TITLE
Does this implementation of Refind has any fixes for serial input? 

### ISSUE THREAD

**Issue by hradec** [dakanji/RefindPlus#60]
**Is your feature request related to a problem? Please describe.**

Running Refind in textmode on a GCE (Google Compute Environment) instance, I can see the menu in the serial connection, but I can't select any options or interact with it any way.

**Describe the solution you would like**

I'm wondering if there is any fixes in this fork regarding serial input.

**Comment by dakanji** [comment]
Please use the Q/A facility under `Discussions` for such questions
