### ISSUE TITLE
SBAT support for secure boot

### ISSUE THREAD

**Issue by diogocardoso28** [dakanji/RefindPlus#71]
**Is your feature request related to a specific problem?**
Secure Boot

**Describe the solution you would like**
SBAT support

**Describe alternatives you have considered**

**Additional context**
Cant get secure boot to work due to the lack os SBAT support

**Comment by dakanji** [comment]
**NOV 2025 UPDATE**
RefindPlus now includes an SBAT section as from v0.14.2.AD.
The binaries just need to be signed and the certificate enrolled.

---

 Unfortunately not on a priority at this time.

You can either submit a patch implementing this for consideration or request this upstream in rEFInd and it will be considered for porting to RefindPlus if/when implemented there,

**Comment by dakanji** [comment]
Users can apparently add such themselves: https://sourceforge.net/p/refind/discussion/general/thread/42495ff081/#4cb4

**Comment by dakanji** [comment]
See this Discussion Item for how to add an SBAT section to Refindplus: https://github.com/dakanji/RefindPlus/discussions/190#discussioncomment-10128642

**NOV 2025 UPDATE**
RefindPlus now includes an SBAT section as from v0.14.2.AD.
The binaries just need to be signed and the certificate enrolled.
