### ISSUE TITLE
RefindPlus Displays Wrong Mac OS Volume Names

### ISSUE THREAD

**Issue by MarioG-X** [dakanji/RefindPlus#73]
**Describe the Bug:**
The RefindPlus menu lists 4 macOS systems on APFS volumes, but displays the same volume name for the last three as you move the cursor (see pics below):
**Monterey Beta, FS 11.5, FS 11.5, FS 11.5**.
Each of the last three boot the _correct_ macOS, but the names should be as described below.

To Reproduce:

Install RefindPlus
Modify config to support APFS
Boot machine

**Expected Behaviour:**
Volume names should be correct:    **Monterey Beta, 10.14.6, FS 10.15.7, FS 11.5.**

**Environment:**
 - RefindPlus Version : v0.13.2.AG
 - Hardware
   * Computer         : Mac mini 2014, Macmini7,1 with internal an SSD and hard drive (originally fusion drive)
   * Motherboard      : Dual-Core Intel Core i7
   * GPU Model        : Intel Iris
 - Affected OS        : All macOS, Opensuse Linux, Elementary OS Linux

**Log Files**
I ran the debug version of RefindPlus and attached the RP log (level 3):
[21r13t2138.log](https://github.com/dakanji/RefindPlus/files/7157047/21r13t2138.log)

**Screenshots**
One for each volume to see volume name:

![IMG_1978](https://user-images.githubusercontent.com/20360699/133150404-d897495f-3e41-4f97-b50f-0c7172771bab.jpeg)
![IMG_1979](https://user-images.githubusercontent.com/20360699/133150413-17b6d664-b355-41b8-836a-ed38ea6b4524.jpeg)
![IMG_1980](https://user-images.githubusercontent.com/20360699/133150419-36a4e78e-eb1b-47a3-a35b-0d75d633e1da.jpeg)
![IMG_1981](https://user-images.githubusercontent.com/20360699/133150432-f0458cf9-6cfa-4b7a-a642-79ddddeb2d28.jpeg)

**Additional Context:**

Here are: diskutil list, diskutil apfs list (rtf files):
[diskutil apfs list.txt](https://github.com/dakanji/RefindPlus/files/7157107/diskutil.apfs.list.txt)
[diskutil list.txt](https://github.com/dakanji/RefindPlus/files/7157108/diskutil.list.txt)

**Comment by dakanji** [comment]
Thanks.

I get what is happening here.

The `SyncAPFS` feature does not work for situations where there is more than one Mac OS instance in the same APFS Container. It basically only works for one instance per container scenarios.

You can work around this issue by disabling the feature in your config file which will make RefindPlus to behave as rEFInd does (no PreBoot Mapping). The next release will try to automatically disable the feature when it detects such a situation. Will get around to trying to actually work with such situations at some point.

BTW, not directly related, but you seem to have Mojave, Catalina and Big Sur in the same APFS Container which is not a good idea as each of those three have different APFS versions. Best avoid this situation.

I will close this issue with a commit later. We can look at the Linux problem in the original issue you raised.

**Comment by MarioG-X** [comment]
Thank you! But syncapfs is the reason I wanted to use RP since there are 5 Preboots  that show in menu.

FYI this is a development machine (I maintain the FreeSwitch macOS wiki) and I never had a problem with multiple macOSs in a single container. I do three because I need the speed of the 128GB SSD on the high use systems, others are on the HD. Nothing important I can't reproduce and I have a gazillion backups. Thanks again and looking forward to trying the next RP.

**Comment by dakanji** [comment]
Got you. Unfortunately this is a current limitation as the system volumes are mapped to PreBoot volumes at a partition level which means one PreBoot for one System volume.

You will need partition the disk for each Mac OS instance for the feature to work (as it currently stands).
