### ISSUE TITLE
Elementary OS partitions don't have correct icons on RP menu

### ISSUE THREAD

**Issue by MarioG-X** [dakanji/RefindPlus#74]
**Describe the Bug:**
This is a minor issue but thought since original refind displays the correct icons so should RP. There are 2 linux Opensuse BTRFS and 2 Linux elementary OS EXT4 partitions. Also 5 macOS volumes in APFS. All display the correct icons except the 2 Elementary OS partitions. 

**To Reproduce:**
Boot RP.

**Expected Behaviour:**
All menu items should display the same as Original Refind does, using the correct icons for Elementary OS.

**Environment:**
RefindPlus Version : v0.13.2.AH beta, AG cannot test because it does not display linux partitions.
Hardware
Computer : Mac mini 2014, Macmini7,1 with internal an SSD and hard drive (originally fusion drive)
Motherboard : Dual-Core Intel Core i7
GPU Model : Intel Iris
Affected OS : All macOS, Opensuse Linux, Elementary OS Linux

**Log Files**
[21r18u2006.log](https://github.com/dakanji/RefindPlus/files/7190466/21r18u2006.log)

**Screenshots**
RP menu, notice the penguin and dimmed elementary os icon:
![IMG_1984](https://user-images.githubusercontent.com/20360699/133905369-e71c77db-aa8e-4ced-a8e0-106998e83708.jpeg)

Original Refind menu, both elementary os icons blue and bright white:
![IMG_1976](https://user-images.githubusercontent.com/20360699/133905381-b38bd0c2-330e-41c8-8ebe-69ccf529f8ed.jpeg)

**Additional Context:**
I found .VolumeIcon.icns and .VolumeIcon.png in "/" (top level root). These display in the original refind menu. I found it odd that although both elementary partitions are identical (one cloned from the other), RP displays a penguin on one and a dimmed elementary icon on the other.

**Comment by dakanji** [comment]
Please use a released version 0.13.2.AG for this issue. The test version of 0.13.2.AH you have access to, has things disabled in terms of icons as was explained and is not a valid basis for this report.

**Comment by MarioG-X** [comment]
As I mentioned above I used the AG version first. Here I tried the AG debug version and it crashed:
[21r18v4659.log](https://github.com/dakanji/RefindPlus/files/7190535/21r18v4659.log)
Going to try a few more tests.

**Comment by dakanji** [comment]
Basically means the report is premature at this point as you have not yet actually been able to definitely confirm that the issue exists since AG does not load Linux and the AH you have is not suitable.

Will close as invalid. You can test when possible to test

**Comment by MarioG-X** [comment]
OK I get it now. No reports of problems in beta, puzzles me because if someone tests beta there is no way to report a new issue. So we wait until you release AH, just thought you may want to prevent a known issue going into AH when it's released.

**Comment by dakanji** [comment]
> OK I get it now. 

Not quite. What you had is not a beta but a file created to test a specific issue which had some distracting items (with respect to the desired test) disabled.

Specifically, this included the loading of some types of icons.

When that items is closed, you can build the code base to get a proper beta that will load linux.

**Comment by dakanji** [comment]
The codebase has been updated with the Linux fixes.

I believe you may have Homebrew installed. If correct, you can build on the current code to verify the issue by following the instructions here: https://github.com/dakanji/RefindPlus#roll-your-own

**Comment by MarioG-X** [comment]
Luckily I have an Xcode "junk" partition to play with, I followed your instructions and built GOP.

RP now displays the same elementary OS icons same as original refind. I booted Opensuse, elementary OS and macOS fine. Great, no work needed on this!  If you're interested here is a log:
[21r19s5637.log](https://github.com/dakanji/RefindPlus/files/7192544/21r19s5637.log)

Don't know if you're interested: I noticed the MBR line for the second drive line was removed, it now has nothing before it instead of showing partition type GUID:
  3:102    0:007  00000000-0000-0000-0000-000000000000  :  00000000-0000-0000-0000-000000000000  :  Unknown          :                     :  Unknown Volume
   3:109    0:007  00000000-0000-0000-0000-000000000000  :  00000000-0000-0000-0000-000000000000  :  Whole Disk       :                     :  Whole Disk Volume

**Comment by dakanji** [comment]
> I noticed the MBR line for the second drive line was removed

That is just down to the logging level


> You have a typo on https://github.com/dakanji/RefindPlus/blob/GOPFix/BUILDING.md first sentence has buidling, should be building.

Will fix. Thanks

BTW, I force pushed a change to the last commit shortly after the original commit. Shouldn't really do that but the repo is not busy and not likely to affect anyone but guess what? Seems you forked the repo between the two pushes and now your fork is out of sync.

Follow the instructions here to bring it back in line:- https://github.com/dakanji/RefindPlus/blob/GOPFix/BUILDING.md#syncing-your-repositories-with-upstream-repositories

**Comment by MarioG-X** [comment]
Thanks for the info but I got this message and will forget about syncing for now, I will set it up a token when I really need it. I can always rebuild RP from scratch if needed (I think) but not likely until SyncAPFS since that was the whole point of converting:
remote: Support for password authentication was removed on August 13, 2021. Please use a personal access token instead.

BTW, I noticed this sentence in the .md, since I verified on Catalina you may want to change it from:
These steps have been verified on Mac OS v10.12 (Sierra) and Mac OS v10.14 (Mojave) and should also work on Mac OS v10.13 (High Sierra) and Mac OS v10.15 (Catalina).

TO:
These steps have been verified on macOS v10.12 (Sierra), macOS v10.14 (Mojave) and macOS v10.15 (Catalina). They should also work on macOS v10.13 (High Sierra), macOS v11 (Big Sur), and macOS v12 (Monterey).

Having said that you may want to remove v12 and v13 because I have found once Apple drops support so does HB and you can no longer build HB packages (most anyway) from scratch.
