### ISSUE TITLE
Allow SyncAPFS to work with multiple macOS system volumes in the same container

### ISSUE THREAD

**Issue by MarioG-X** [dakanji/RefindPlus#75]
**Is your feature request related to a specific problem?**
It's not practical to put macOSs in their own container and own partition with many partitions, I may have up to 10 macOSs on a test machine, and several Linux's. On top of that, I have an HD and SSD with 3 containers, need to write down all the Preboot locations on paper, or boot the wrong one often since they change location often on a test machine. APFS makes life easy.

**Describe the solution you would like**
Allow RP to use SyncAPFS for multiple macOS boot volumes in the same container.

**Describe alternatives you have considered**
There are none currently.

**Additional context**
None

**Comment by dakanji** [comment]
Please try X175
[X175-BOOTx64.efi.zip](https://github.com/dakanji/RefindPlus/files/7204422/X175-BOOTx64.efi.zip)

Note that this is also a narrow focus build for this specific item.
Main thing you will notice is that it will work in text mode. You should still be able to identify whether the volumes are shown as required.

**Comment by MarioG-X** [comment]
Missing menu items for Monterey Beta and FS 11.6. Tested booting into last Preboot which turned out to be FS 11.6.
[21r21u5948.log](https://github.com/dakanji/RefindPlus/files/7205596/21r21u5948.log)

![IMG_1785](https://user-images.githubusercontent.com/20360699/134232369-97336571-7ab6-4957-8ec1-04de84a5bd29.jpeg)

![IMG_1786](https://user-images.githubusercontent.com/20360699/134232377-18c6dbff-2178-4210-b910-6b29049bfffa.jpeg)

**Comment by dakanji** [comment]
Thanks. Seems Apple changed something in later versions. X176 should catch more.
[X176-BOOTx64.efi.zip](https://github.com/dakanji/RefindPlus/files/7206323/X176-BOOTx64.efi.zip)

**Comment by MarioG-X** [comment]
Getting better but the screen below has 3 issues:

1. The "Monterey Beta" system is missing, could be the first Preboot should be "Monterey Beta".
2. What was the second Preboot now shows as a blank line (see first pic), then as soon as you move the cursor it changes to "FS 11.6" (see second pic). I booted this entry fine into macOS on FS 11.6.
3. I think there should be recovery entries for "Monterey Beta" and "FS 11.6". They are in different containers.

![IMG_1787](https://user-images.githubusercontent.com/20360699/134263684-6f8a5bd7-570f-46b7-ba44-26c23918978a.jpeg)

![IMG_1788](https://user-images.githubusercontent.com/20360699/134263704-ebd9e6eb-4dee-4127-8c65-607283faca63.jpeg)

**Comment by dakanji** [comment]
Thanks for the feedback

> The "Monterey Beta" system is missing, could be the first Preboot should be "Monterey Beta".

- The first PreBoot is not as you found out. 
- Monterey Beta is misnamed as the first "10.14.6". Don't know why as yet.

> What was the second Preboot now shows as a blank line 

- That is just a glitch in the text mode screen where the default item selected on screen load does not display until the selection is moved. Still trying to figure why out that. If you go into 'About RefindPlus' and come back, you will see that effect on the selection. Doesn't affect graphics mode.

> I think there should be recovery entries for "Monterey Beta" and "FS 11.6". 

- RP has found and listed the recovery options available.
- You will note that the ones for versions up to 10.15 are shown individually but that for 11.6 and Monterey seem to have been combined.
- BTW, the code that was added to identify the volumes in the multi-volume container scenario was leveraged to identify the recovery instances (default is for all to have a generic name such as the first one) but something appears to have changed in 11.6 and Monterey in how this works and the recovery entry cannot be mapped to a Mac OS instance for those versions in the way that works for the others and I think, up to 11.5.

Back to the first PreBoot entry, this is a new instance (presumably added after a recent update) that behaves differently to the others. Not sure if it is an artefact of the update process but it also, like the recovery item discussed earlier, cannot be mapped to a specific system volume. It is not pointing to any volume visible to RP. I can change things to just not show it though. Needs testing on other installations.

I am half inclined to ditch the effort and go back to the limited scope but more resilient implementation (within its scope). Can perhaps take another look at this when what looks like ongoing changes to APFS by Apple settle down ... possibly sometime after Monterey comes out.

Can you run rEFInd to check whether a new PreBoot items shows up though? Also check how many recovery items it finds.

Will make a call on things later.

**Comment by MarioG-X** [comment]
Answers and info:

Yes there were updates but the diskutil list and original refind displays the same as before:
1. Updated 11.5 with security updates to 11.6, and renamed volume from 11.5 to 11.6.
2. Updated 10.15.7 with Apple security update.
3. Had created a backup system volume from 11.6 to disk3 container, then deleted it after test, diskutil shows no change.

Here is a diskutil list, you will find that it is identical to the one in the previous issue I sent except 11.5 is now renamed 11.6:
[duskutil2.list.txt](https://github.com/dakanji/RefindPlus/files/7210377/duskutil2.list.txt)

Original refind can boot all Preboot partitions. Here is the original refind log:
[refind.log](https://github.com/dakanji/RefindPlus/files/7210414/refind.log)

Below is a screen print of original refind. It is also identical to the one before the previously mentioned changes (original screen in previous issue). I tested booting from _all Preboots_ and they _work_.  Notice that original refind shows 4 recovery partitions with no name. RP shows the first as "Recovery" but the next three properly named, I did not test these.

The sequence of the macOSs in original refind are:
1. FX 10.15.7 Xcode
2. Preboot (boots Monterey)
3. Monterey Beta
4. Preboot (boots FX 10.15.7 Xcode)
5. Preboot (boots FS 10.15)
6. Preboot (boots FS 11.6)
7. FS 10.14.6 (not bootable from this entry)
8. FS 10.15.7 (not bootable from this entry)
9. FS 11.6 (not bootable from this entry)

![IMG_1988](https://user-images.githubusercontent.com/20360699/134339161-e4242664-9e83-48d4-ab50-23e24d7fadbf.jpeg)

![IMG_1989](https://user-images.githubusercontent.com/20360699/134339262-9f8c32db-1a30-43b9-811a-cc02be393acf.jpeg)

**Comment by dakanji** [comment]
Thanks

> Yes there were updates but the diskutil list and rEFInd displays the same as before:

The changes are under the hood and Apple's diskutil will have been adjusted to display the same final output while rEFInd was never doing anything special with APFS so yes, no change expected in either.

> Here is a diskutil list, you will find that it is identical to the one in the previous issue 
yeah ... expected. 

> Below is a screen print of rEFInd. It is also identical to the one before the previously mentioned changes (original screen in previous issue). I tested booting from all Preboots and they work. 

> Notice that rEFInd shows 4 recovery partitions with no name. 

Confirms there is not longer a 1 to 1 pattern of System and Recovery volume. This appears to be something new with the recent update.

Anyway, please try X177 which fixes a bug in the last one spotted and will not show that first PreBoot if still present.
[X177-BOOTx64.efi.zip](https://github.com/dakanji/RefindPlus/files/7210769/X177-BOOTx64.efi.zip)

**Comment by MarioG-X** [comment]
Sorry for the long lag, it was 4:30AM when I last posted, needed sleep, now 8:15.

First the good news, Monterey Beta displays and booted! And Big Sur 11.6 also. The issues now:
1. The default still shows as a blank line (see first pic), then as soon as you move the cursor it changes to "FS 11.6" (see second pic). I booted this entry fine into macOS on "FS 11 5 - Data".
2. The volume name for "Monterey Beta" displays as "Monterey Beta - Data" instead of the system volume name.
3. The volume name for "FS 11.6" displays as "FS 11 6 - Data" instead of "FS 11.6", the actual system volume.

Notice the correct names were displayed for the two in 176.

Before Pressing a key:
![IMG_1991](https://user-images.githubusercontent.com/20360699/134371371-ea3a0be1-766e-44a2-b550-6200ad8ef27b.jpeg)

After pressing key:
![IMG_1992](https://user-images.githubusercontent.com/20360699/134371439-207cb469-a087-4a3b-9474-a6aaac1d35c6.jpeg)

**Comment by dakanji** [comment]
Brilliant. Working as expected.

APFS differs between Mac OS versions and continues to evolve. While mixing versions in a container may not yet have led to issues, this is almost certainly inevitable.

A change was made with Mac OS 11.6 and the PreBoot volume now points to the data volume and not the system volume.

Anyway, just need to test on some other setups

**Comment by MarioG-X** [comment]
Great! When you get closer to final, I will test boot all partitions as well as some on one of my externals which have several bootable partitions. BTW, I did test 176 booting an external and it found all volumes.

**Comment by MarioG-X** [comment]
Does that mean you want a final test from me? If so, what should I download? Thanks.

**Comment by dakanji** [comment]
Not strictly necessary but if you do want to test it, that was a push of the code which can now be built.

**Comment by MarioG-X** [comment]
Man, dakanji you rock! Here is some information you may be pleased to know that testing was all good!:

Only minor issue is the the " Data" volume is displayed, not a biggie since it can be renamed. Could be related to macOS "sealed" system volumes. Still WAY better than hunt and peck Preboots!

Tested Linux systems:
	1	OpenSuse 15.3         BTRFS
	2	OpenSuse 15.3 - 2   BTRFS
	3	Elementary OS         EXT4
	4	Elementary OS - 2   EXT4

Tested macOS (all APFS):
	5	FX 10.15.7 Xcode
	6	Monterey Beta - Data
	7	FS 10.14.6 
	8	FS 10.15.7
	9	FS 11 6 - Data

External booted a macOS 10.14.6 volume

A log if desired:
[21r23x3124.log](https://github.com/dakanji/RefindPlus/files/7220947/21r23x3124.log)

Boot screen, no external connected:
![IMG_1789](https://user-images.githubusercontent.com/20360699/134588088-82cf931f-88c9-432d-b98f-c3b147218465.jpeg)

**Comment by dakanji** [comment]
> not a biggie since it can be renamed

See: https://github.com/dakanji/RefindPlus/blob/d87d3fb3b46787440c6dace431b1a6a3517161a9/config.conf-sample#L41-L44

**Comment by MarioG-X** [comment]
I just thought that when the Mac is booted with the option key and it shows "FS 11.6", Monterey Beta" and not the data volumes it may be easy to implement. I'm pleased as punch it works with - Data so no biggie. BTW, I tested booting 10.15.7 and 11.6 from an external and edited notes above.

**Comment by dakanji** [comment]
The " - Data" string will be filtered out later for display. 
Obviously can't cover every language as it differs by localisation but set up for English and German as a start.

**Comment by MarioG-X** [comment]
May I suggest to leave it as is rather than simply removing the "- Data" because the names may still be different. For instance, my 11.6 volumes were "FS 11.6" (because I renamed from 11.5 after the update), and the attached volume stayed "FS 11 5 - Data". Just stripping "- Data" would result in "FS 11 5" which may be confusing, especially if there was a real _11.5 and 11.6_ on the system. I would prefer leaving it as is if the correct system volume name can't be obtained.

**Comment by dakanji** [comment]
That seems to be more of a problem with your setup.
It is not standard to keep changing the name of an installation volume to match updates.

**Comment by MarioG-X** [comment]
No problem with my setup, on two machines that I used for heavy testing. macOS allows you to change the system volume name anytime, but the data volume will stay unchanged. This will cause issues, I've seen it on the web many times. No harm in using the real - Data volume name so it's obvious what is booting. Removing "- Data" is asking for issues later on IMHO.

**Comment by dakanji** [comment]
I know that Mac OS allows changing volume names. The problem I meant was doing this with every update. Most users probably never change the name once set.

Any way, the filtering will be to try to change the displayed name to the system volume name ... so even your approach should be fine.

**Comment by MarioG-X** [comment]
I just remembered that at one point (see screen above) the system volume name displayed on the RP menu so it must be available. You could use that for the menu and the name in Preboot for actual booting. See the screen above:
https://user-images.githubusercontent.com/20360699/134263704-ebd9e6eb-4dee-4127-8c65-607283faca63.jpeg

**Comment by MarioG-X** [comment]
Add to above:
There is another issue to my previous kludgy technique of simply stripping "- Data" (which I wound up abandoning and solving many issues): When macOS creates the - Data volume, it strips certain characters like periods and others, for example, my volumes are names contain a v.r.m like 11.6, 11.5.1, 12.15.7, etc, If a data volume is created at that level, the periods (and other specula characters if used) are stripped. Even if the data volume is never renamed, it is called "11 6", "11 5 1", etc. Other who may use a special character in the system volume would see a strange name. Using the correct name solves this issue as well as when the system volume name is renamed. You have been a perfectionists so far, I recommend leaving the - Data name in place if there is no way to associate the two volumes. Wish we knew how the Mac firmware does it since it displays the correct name in the option/boot menu.

And again, many thanks for your work!

**Comment by dakanji** [comment]
> You have been a perfectionist

You have me wrong there as I lean heavily to the pragmatist side of things. This means not dropping something that will benefit the 99.9% for the sake of the 0.1%. 

In this particular edge case however, I think that by pure chance of the implementation approach, you will end up with the Data Volume name unchanged.

The feature has been completed and pushed. You can build and see what you get but sorry, if it does not end up as I think it will (with the data volume name intact for your case), you will have to reevaluate your volume naming scheme and perhaps consider dropping special characters.

**Comment by MarioG-X** [comment]
No problem, it's WAY better than a bunch of changing Preboots! Forgive my concerns, having been a mainframe programmer who developed for hospitals and banks for 40 years, only 100 percent perfect in all conditions is acceptable is what I am used to. Many thanks again!

**Comment by dakanji** [comment]
I am sure that if RP was being developed by a corporation with a team of paid experts, it would also aim for being 100% perfect under any and every conceivable condition.

I'm afraid that in this case however, we have to settle for a target of mere a 100% perfect under all ***supported*** conditions and at this point in time, that particular edge case condition is not supported (although as said, I am pretty sure the anticipated issue will not materialise ... for now).

**Comment by MarioG-X** [comment]
Actually, I would have thought many people using RP are developers who are likely to do exactly what I do with several volumes on a Mac. As for supported, macOS supports it fine, if you mean RP supported conditions that's different and we just have to live with it.

 If you're set on not using the actual system volume name, then real Data volume name should be displayed instead of displaying _**a non existent volume,**_ "FS 11.5 - Data" should not be displayed as "FS  11 5" when there is no such volume, simply display "FS 11 5 - Data", a volume that actually exists.

**Comment by dakanji** [comment]
Too complicated to explain in detail but at a high level, you are not booting the system or data volume whatever label RP puts there ... you are booting the PreBoot volume.

Anyway, not much point discussing this item further as the actions have been taken and I will like to move on to other items.

Thanks for your assistance though.
