### ISSUE TITLE
MyFreePool Does Not Work as Intended

### ISSUE THREAD

**Issue by dakanji** [dakanji/RefindPlus#81]
### RefindPlus Version

v0.13.2.AJ Release

### Device Type

Apple Mac

### Problem Description

As notified by @joevt on another channel, the `MyFreePool` and `ReleasePtr` functions are not operational due to an inaccuracy. Hence, memory pool items passed to either function do not get freed as intended.

### Problem Point

Other

### Affected Items

Other Item

### Debug Log and (Optional) Screenshots

Not Applicable

**Comment by startergo** [comment]
Shouldn't the title be "does not work as intended"?
