### ISSUE TITLE
Allow Setting Background Colour in Config File

### ISSUE THREAD

**Issue by ywjheart** [dakanji/RefindPlus#87]
### Suggested Feature

Refind default to a white background when no theme or a background image is used, that is very bright at night.
I hence request a feature that allows to tweak this by allow to set RGB color in hex form, say,
background_color 808080

**Comment by dakanji** [comment]
Thanks.

RefindPlus does not default to white but to grey. I suppose this might qualify as bright as well but is there any reason why a simple image cannot be used?

For instance, a small screen grab with the colour you want in the icons folder and the screen will take that colour.

**Comment by ywjheart** [comment]
Yes, a small solid color image works. However, not perfect. seems refind reset frame buffer with a white solid color before filling the image, it causes screen flickering. I think a customised color can overcome this.

**Comment by dakanji** [comment]
Are you sure you are using RefindPlus as opposed to rEFInd? 

In any case, there is no solid white colour stage in the process of either of the two. If you are seeing such, this must be something your firmware does before RefindPlus loads and this will be there even with the option you want.

I.E., allowing the background colour to be set in the config file will not remove this. Interesting idea but will not give the solution you want.

**Comment by ywjheart** [comment]
Yes. I am using refineplus with config.conf
Both refindit and refineplus have the problem.
It is likely related to motherboard EFI and gpu EFI.

**Comment by dakanji** [comment]
> Both rEFInd and RefinedPlus have the problem

Technically, not a problem of either since it is not something they are doing.
Most computers show a solid black screen in such cases and perhaps you should look into your BIOS settings.

However, the idea of being able to set the background colour from the config seems interesting even if not related to your specific problem. Will take a look at this.

**Comment by ywjheart** [comment]
Noted
