### ISSUE TITLE
Allow to hide entries no matter its source

### ISSUE THREAD

**Issue by ywjheart** [dakanji/RefindPlus#88]
### Suggested Feature

The current refindplus doesn't allow to hide an entry if it is a manual boot stanza. The limitations should be removed, hiding should work like a visibility control after scanning.

### Background Information

I my use case, boot menu always contains an Ubuntu entry, it is used to fix system issues, either Ubuntu system or an Ubuntu iso/sfs file, I was using GRUB before moving to refindplus. 

### Additional Context

Using env variables and if-else statement can turn off entries. in GRUB UI, press C to enter bash like environment, and use set and save_env to change an environment variable.

example:
set ubuntu_iso=0
save_env ubuntu_iso

the boot entry is removed when reload the config file or simply reboot system. similarly set ubuntu_iso=1 to turn it on again.

example GRUB config:
set ubuntu_iso=0
set ubuntu_sfs=1

if [ -s $prefix/grubenv ]; then
	set have_grubenv=true
	load_env saved_entry ubuntu_iso ubuntu_sfs
fi
if [ "${saved_entry}" ] ; then
	set default="${saved_entry}"
fi

function savedefault {
	saved_entry="${chosen}"
	save_env saved_entry
}

if [ $ubuntu_iso -eq 1 ]; then
menuentry "Ubuntu iso" --class "Ubuntu" --id ubuntuiso {
	rmmod tpm
	set gfxpayload=keep
	set isofile=/ubuntu-20.04.3-desktop-amd64.iso
	search --no-floppy --set=disk --label linux_data
	loopback loop ($disk)$isofile
	linux	(loop)/casper/vmlinuz boot=casper iso-scan/filename=$isofile fsck.mode=skip noeject noprompt amdgpu.modeset=1
	initrd	(loop)/casper/initrd
}
fi

if [ $ubuntu_sfs -eq 1 ]; then
menuentry "Ubuntu sfs" --class "Ubuntu" --id ubuntusfs {
	rmmod tpm
	set gfxpayload=keep
	set dir=ubuntu_20.04.3
	set sysfile=/$dir/filesystem.squashfs
	search --no-floppy --set=disk --label linux_data
	linux	($disk)/$dir/vmlinuz boot=casper live-media=/dev/sda4 live-media-path=$dir fsck.mode=skip noeject noprompt amdgpu.modeset=1
	initrd	($disk)/$dir/initrd
}
fi

**Comment by dakanji** [comment]
I understand the request but it is a low priority item if it will be done.
If you don't need the stanza, disable it in the config.

Understood as said though.

**Comment by ywjheart** [comment]
Noted

**Comment by dakanji** [comment]
Had a closer look at this and sorry, but just adds a layer of complexity.
