### ISSUE TITLE
Allow to set display order with key -=

### ISSUE THREAD

**Issue by ywjheart** [dakanji/RefindPlus#91]
### Suggested Feature

entries from different source are hard to sorted nicely, currently they are added according scan/detection order. I think can add an attribute to entry: order, which could be any number.
manual entry can set a static value, so all non-manual has a built-in static value 0.
press - or = to increase/decrease the dynamic order value.
the final sort value = the value set in refindplus UI + static value. 
as the result all items can be sorted nicely.

**Comment by dakanji** [comment]
Thanks. An interesting idea but need to focus on pending stability issues for a while.
Will get back to reconsider this later.

**Comment by dakanji** [comment]
Took a look at this and will not be making the requested changes.
You can arrange the items in the config files as you want them to a large extent.
