### ISSUE TITLE
v0.13.2.AL Shows Wrong APFS Volume Names (Boots into Correct Instances)

### ISSUE THREAD

**Issue by MarioG-X** [dakanji/RefindPlus#93]
### RefindPlus Version

v0.13.2.AL Release

### Device Type

Apple Mac

### Problem Description

AK did not have this issue: Using the non-debug version (debug hangs) the list of volumes displays with correct icons, but when you tab from one to the other it displays the wrong names, one duplicated multiple times. When I select a volume to boot, it booted the correct volume, just not the one shown as the name.

The correct list as shown by AK:
OpenSuse BUM, OpenSuse BU, Elementary, FS 10.15.7 Xcode, Monterey, FS 10.15.7, Big Sur

The names shown by AL:
OpenSuse BUM, OpenSuse BU, Elementary, FS 10.15.7 Xcode, FS 10.15.7 Xcode, FS 10.15.7 Xcode, FS 10.15.7, FS 10.15.7 Xcode

The log RP shows the correct APFS volumes early on, but then uses incorrect names later:

   4:244    0:006  ReMap APFS Volumes:
                     - System Volume:- 'FX 10.15.7 Xcode'
                     - System Volume:- 'Big Sur DL'
                     - System Volume:- 'Monterey'
                     - System Volume:- 'FS 10.15.7'
                     - System Volume:- 'FS Big Sur'

===================[ Assign Shortcut Keys ]===================
  11:182    0:009  Set Key '1' to Boot boot\vmlinuz-5.3.18-59.37-default from Vsuse153bum
  11:185    0:003  Set Key '2' to Boot boot\vmlinuz-5.3.18-59.37-default from Vsuse153bu
  11:189    0:004  Set Key '3' to Boot boot\vmlinuz-5.11.0-40-generic from Velementary
  11:193    0:003  Set Key '4' to Boot Mac OS from FX 10.15.7 Xcode
  11:196    0:003  Set Key '5' to Boot Mac OS from FX 10.15.7 Xcode
  11:199    0:003  Set Key '6' to Boot Mac OS from FX 10.15.7 Xcode
  11:203    0:003  Set Key '7' to Boot Mac OS from FS 10.15.7
  11:206    0:003  Set Key '8' to Boot Mac OS from FX 10.15.7 Xcode

### Problem Point

While starting a loader or tool

### Affected Items

Mac OS Loader

### Debug Log

Unavailable since the AL debug version hangs. See #92.

**Comment by dakanji** [comment]
OK. Seems the Enhancements to APFS needs more work. The other issue is part of this so will close that.

**Comment by dakanji** [comment]
Please Try X180 ... It is a debug build
[X180-BOOTx64.efi.zip](https://github.com/dakanji/RefindPlus/files/7699888/X180-BOOTx64.efi.zip)

**Comment by MarioG-X** [comment]
X180 fixed both issues. I tested booting: Opensuse BTRFS (with AL driver), Elementary (with AL driver), macOS Monterey and Big Sur. Here is last log in case it's useful:
[21x12y3142.log](https://github.com/dakanji/RefindPlus/files/7700003/21x12y3142.log)

**Comment by dakanji** [comment]
Was an attempt to better accommodate some, not naming names, that insist on putting multiple APFS instances in a container. 

Basically thought a known unique ID had been found but was obviously not the case this time.
Clearly possible but seems to need more work.

It was a port of downstream code and already notified the dev. 
Rolled back to my old implementation in X180 ... Will release shortly.

Thanks.

**Comment by MarioG-X** [comment]
No rush, AK works fine. On almost every Mac forum where it's discussed, people put multiple bootable volumes in a single container. Right now a lot of people putting Monterey along side Big Sur because when you install Monterey you can put it into a new volume which many people do. The only container that came with the machine if no changes were made, no need for more static partitions.

I keep an eye for new RP releases and try to test on a Mini and iMac (both linux and macOS) in the first day or two. If you don't hear from me it's good on these machines.

**Comment by dakanji** [comment]
Nothing wrong with doing that per se, just more challenging to deal with.
There is some sort of unique ID, VolumeGroupID, that ties the components and it seemed this had been retrieved but it turned out not to be the case.

There is lot of workaround going on in the background to do stuff when the volumes are together. This has a limit and getting this ID would have removed the need for such.

**Comment by joevt** [comment]
What kind of Mac are you using?
Where is the apfs.efi driver loaded from? I was testing this with a Mac mini 2018.
I'll need to do more testing with my Mac Pro 2008 with various versions of the apfs.efi driver.

Can you post the result of `diskutil apfs list` ?

Each macOS version has its own /usr/standalone/i386/apfs.efi driver which it embeds into the APFS container. I think RefindPlus can be using the driver from firmware, or apfs container, or from the RefindPlus drivers folder.
I suppose some of these might not return the VolumeGroup. Instead of being dependant on the apfs.efi driver version, RefindPlus could just read the VolumeGroup directly from the APFS volume block device.

**Comment by MarioG-X** [comment]
joevt, Mini 2014 list is below. Have no idea where apfs.efi is loaded from, it's not in drivers folder.

This will change today with the release of 12.1:
/dev/disk0 (internal, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *121.3 GB   disk0
   1:                        EFI ⁨EFI⁩                     209.7 MB   disk0s1
   2:                 Apple_APFS ⁨Container disk2⁩         121.1 GB   disk0s2

/dev/disk1 (internal, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *2.0 TB     disk1
   1:                        EFI ⁨EFI⁩                     209.7 MB   disk1s1
   2:                 Apple_APFS ⁨Container disk4⁩         1.0 TB     disk1s2
   3:                 Apple_APFS ⁨Container disk3⁩         200.1 GB   disk1s3
   4:                  Apple_HFS ⁨Open 291⁩                291.8 GB   disk1s4
   5:                  Apple_HFS ⁨⁩                        49.9 GB    disk1s5
   6:           Linux Filesystem ⁨⁩                        49.9 GB    disk1s6
   7:                  Apple_HFS ⁨⁩                        49.9 GB    disk1s7
   8:           Linux Filesystem ⁨⁩                        49.9 GB    disk1s8
                    (free space)                         134.2 MB   -
   9:                  Apple_HFS ⁨⁩                        49.9 GB    disk1s9
  10:                  Apple_HFS ⁨⁩                        249.9 GB   disk1s10
  11:                 Linux Swap ⁨⁩                        7.9 GB     disk1s11

/dev/disk2 (synthesized):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      APFS Container Scheme -                      +121.1 GB   disk2
                                 Physical Store disk0s2
   1:                APFS Volume ⁨FS 10.15.7⁩              11.3 GB    disk2s2
   2:                APFS Volume ⁨FS Big Sur - Data⁩       11.5 GB    disk2s3
   3:                APFS Volume ⁨Preboot⁩                 544.6 MB   disk2s4
   4:                APFS Volume ⁨Recovery⁩                1.2 GB     disk2s5
   5:                APFS Volume ⁨FS 10157 - Data⁩         10.4 GB    disk2s6
   6:                APFS Volume ⁨VM⁩                      2.1 GB     disk2s7
   7:                APFS Volume ⁨FS Big Sur⁩              15.3 GB    disk2s9
   8:              APFS Snapshot ⁨com.apple.os.update-...⁩ 15.3 GB    disk2s9s1

/dev/disk3 (synthesized):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      APFS Container Scheme -                      +200.1 GB   disk3
                                 Physical Store disk1s3
   1:                APFS Volume ⁨Monterey - Data⁩         15.7 GB    disk3s1
   2:                APFS Volume ⁨Preboot⁩                 270.1 MB   disk3s2
   3:                APFS Volume ⁨Recovery⁩                1.1 GB     disk3s3
   4:                APFS Volume ⁨VM⁩                      1.1 MB     disk3s4
   5:                APFS Volume ⁨Monterey⁩                15.7 GB    disk3s5

/dev/disk4 (synthesized):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      APFS Container Scheme -                      +1.0 TB     disk4
                                 Physical Store disk1s2
   1:                APFS Volume ⁨FX 10.15.7 Xcode - Data⁩ 40.7 GB    disk4s1
   2:                APFS Volume ⁨FX 10.15.7 Xcode⁩        11.2 GB    disk4s2
   3:                APFS Volume ⁨Preboot⁩                 546.7 MB   disk4s3
   4:                APFS Volume ⁨Recovery⁩                1.2 GB     disk4s4
   5:                APFS Volume ⁨VM⁩                      9.7 GB     disk4s5
   6:                APFS Volume ⁨Big Sur DL⁩              15.3 GB    disk4s6
   7:                APFS Volume ⁨Big Sur DL - Data⁩       29.6 GB    disk4s7

/dev/disk5 (external, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *256.1 GB   disk5
   1:                        EFI ⁨EFI⁩                     209.7 MB   disk5s1
   2:                  Apple_HFS ⁨Install macOS Monterey⁩  255.7 GB   disk5s2

**Comment by MarioG-X** [comment]
mario@FS-Big-Sur local % diskutil info -all | egrep -i "identifier|UUID|group|Volume Name|\*"
   Device Identifier:         disk0
   Volume Name:               Not applicable (no file system)
**********
   Device Identifier:         disk0s1
   Volume Name:               EFI
   Volume UUID:               0E239BC6-F960-3107-89CF-1C97F78BB46B
   Disk / Partition UUID:     4F712490-0A4A-40D9-82A2-6E9B02D7932B
**********
   Device Identifier:         disk0s2
   Volume Name:               Not applicable (no file system)
   Disk / Partition UUID:     295D77E2-DF08-4EA1-A39B-3550D27DE6C0
**********
   Device Identifier:         disk1
   Volume Name:               Not applicable (no file system)
**********
   Device Identifier:         disk1s1
   Volume Name:               EFI
   Volume UUID:               0E239BC6-F960-3107-89CF-1C97F78BB46B
   Disk / Partition UUID:     F609E2DF-696A-4889-8FF1-A684F611B77A
**********
   Device Identifier:         disk1s2
   Volume Name:               Not applicable (no file system)
   Disk / Partition UUID:     3B3E8E1B-2381-43F5-B9AE-5F9EAB79EF93
**********
   Device Identifier:         disk1s3
   Volume Name:               Not applicable (no file system)
   Disk / Partition UUID:     DCDD7435-30E8-4989-BB3C-30B1D767F9D6
**********
   Device Identifier:         disk1s4
   Volume Name:               Open 291
   Volume UUID:               062A2E46-CBC4-324C-9620-DE3092238084
   Disk / Partition UUID:     F6F9F909-3E73-4C2C-B362-50FEBE7E8B60
**********
   Device Identifier:         disk1s5
   Volume Name:               
   Disk / Partition UUID:     B3223404-A23F-47EE-9B32-B18127DBB4D4
**********
   Device Identifier:         disk1s6
   Volume Name:               Not applicable (no file system)
   Disk / Partition UUID:     B5BDA425-2901-44A6-AEFE-5E4AC6B6A5A0
**********
   Device Identifier:         disk1s7
   Volume Name:               
   Disk / Partition UUID:     62BBDA90-1A18-4AFC-91B7-A876B5846891
**********
   Device Identifier:         disk1s8
   Volume Name:               Not applicable (no file system)
   Disk / Partition UUID:     3C388E87-DB9D-4293-8DF0-2A1527107036
**********
   Device Identifier:         disk1s9
   Volume Name:               
   Disk / Partition UUID:     405FAE3A-0A05-4468-ADC6-0455DFBFB1BC
**********
   Device Identifier:         disk1s10
   Volume Name:               
   Disk / Partition UUID:     0561F465-A6EF-47B7-8761-2B949C520F9C
**********
   Device Identifier:         disk1s11
   Volume Name:               
   Disk / Partition UUID:     C697AB69-56AE-4F5F-B539-E15569C843DD
**********
   Device Identifier:         disk2
   Volume Name:               Not applicable (no file system)
   Disk / Partition UUID:     ADAF3541-DB3E-4810-AB11-EA67CD5BCFF0
**********
   Device Identifier:         disk2s1
   Volume Name:               FS Monterey - Data
   Volume UUID:               4E8B3EA1-DDB6-4FAD-930A-2B217366D737
   Disk / Partition UUID:     4E8B3EA1-DDB6-4FAD-930A-2B217366D737
   APFS Volume Group:         4E8B3EA1-DDB6-4FAD-930A-2B217366D737
**********
   Device Identifier:         disk2s2
   Volume Name:               FS Catalina
   Volume UUID:               23A0B611-65E4-4B2C-A536-9DF8D499B3E5
   Disk / Partition UUID:     23A0B611-65E4-4B2C-A536-9DF8D499B3E5
   APFS Volume Group:         09201E22-0AA1-4C81-B4E8-A19C09410A9D
**********
   Device Identifier:         disk2s3
   Volume Name:               FS Big Sur - Data
   Volume UUID:               959FEA64-00B3-4474-8EF7-A29ABD0A00DE
   Disk / Partition UUID:     959FEA64-00B3-4474-8EF7-A29ABD0A00DE
   APFS Volume Group:         959FEA64-00B3-4474-8EF7-A29ABD0A00DE
**********
   Device Identifier:         disk2s4
   Volume Name:               Preboot
   Volume UUID:               A020A66C-C0A9-469B-859E-2EA6A28FBF9F
   Disk / Partition UUID:     A020A66C-C0A9-469B-859E-2EA6A28FBF9F
**********
   Device Identifier:         disk2s5
   Volume Name:               Recovery
   Volume UUID:               866E5EE5-4895-4A96-ADC8-CB8A075D5857
   Disk / Partition UUID:     866E5EE5-4895-4A96-ADC8-CB8A075D5857
**********
   Device Identifier:         disk2s6
   Volume Name:               FS Catalina - Data
   Volume UUID:               09201E22-0AA1-4C81-B4E8-A19C09410A9D
   Disk / Partition UUID:     09201E22-0AA1-4C81-B4E8-A19C09410A9D
   APFS Volume Group:         09201E22-0AA1-4C81-B4E8-A19C09410A9D
**********
   Device Identifier:         disk2s7
   Volume Name:               VM
   Volume UUID:               11506EBB-B0F2-46BB-A905-1B8B2BEE948D
   Disk / Partition UUID:     11506EBB-B0F2-46BB-A905-1B8B2BEE948D
**********
   Device Identifier:         disk2s8
   Volume Name:               Update
   Volume UUID:               1D8F039D-ACAF-4585-9B86-0A76C03A289A
   Disk / Partition UUID:     1D8F039D-ACAF-4585-9B86-0A76C03A289A
**********
   Device Identifier:         disk2s9
   Volume Name:               FS Big Sur
   Volume UUID:               D3952D36-8FEC-4782-9459-28E44C2F119D
   Disk / Partition UUID:     D3952D36-8FEC-4782-9459-28E44C2F119D
   APFS Volume Group:         959FEA64-00B3-4474-8EF7-A29ABD0A00DE
**********
   Device Identifier:         disk2s9s1
   Volume Name:               FS Big Sur
   Volume UUID:               A97A70B3-54BE-4D19-85E4-23199EE6C884
   Disk / Partition UUID:     A97A70B3-54BE-4D19-85E4-23199EE6C884
   APFS Snapshot UUID:        A97A70B3-54BE-4D19-85E4-23199EE6C884
   APFS Volume Group:         959FEA64-00B3-4474-8EF7-A29ABD0A00DE
**********
   Device Identifier:         disk2s10
   Volume Name:               FS Monterey
   Volume UUID:               E036D982-47E1-4B0C-9CFC-0BC84398AFA7
   Disk / Partition UUID:     E036D982-47E1-4B0C-9CFC-0BC84398AFA7
   APFS Volume Group:         4E8B3EA1-DDB6-4FAD-930A-2B217366D737
**********
   Device Identifier:         disk3
   Volume Name:               Not applicable (no file system)
   Disk / Partition UUID:     F7B8D38A-C4F2-4A8D-930F-C526107A3F70
**********
   Device Identifier:         disk3s1
   Volume Name:               Monterey
   Volume UUID:               780FEB66-3045-47FF-88B1-49E284EC2B09
   Disk / Partition UUID:     780FEB66-3045-47FF-88B1-49E284EC2B09
   APFS Volume Group:         C7057A6F-18A1-4A9F-9B38-FDD582250D81
**********
   Device Identifier:         disk3s2
   Volume Name:               Preboot
   Volume UUID:               BEC2B9D7-CB84-4AF4-B00F-B64D4C58F42A
   Disk / Partition UUID:     BEC2B9D7-CB84-4AF4-B00F-B64D4C58F42A
**********
   Device Identifier:         disk3s3
   Volume Name:               Recovery
   Volume UUID:               0CF9B297-4018-4F00-8A1C-1E1F6F416C24
   Disk / Partition UUID:     0CF9B297-4018-4F00-8A1C-1E1F6F416C24
**********
   Device Identifier:         disk3s4
   Volume Name:               VM
   Volume UUID:               3DAB4CB9-C505-459A-81D4-D6938B0CE538
   Disk / Partition UUID:     3DAB4CB9-C505-459A-81D4-D6938B0CE538
**********
   Device Identifier:         disk3s5
   Volume Name:               Monterey - Data
   Volume UUID:               C7057A6F-18A1-4A9F-9B38-FDD582250D81
   Disk / Partition UUID:     C7057A6F-18A1-4A9F-9B38-FDD582250D81
   APFS Volume Group:         C7057A6F-18A1-4A9F-9B38-FDD582250D81
**********
   Device Identifier:         disk3s6
   Volume Name:               Update
   Volume UUID:               484A3673-8F20-4D46-BD3C-4B78937218B2
   Disk / Partition UUID:     484A3673-8F20-4D46-BD3C-4B78937218B2
**********
   Device Identifier:         disk4
   Volume Name:               Not applicable (no file system)
   Disk / Partition UUID:     D965A8E7-3260-4AE2-A8EE-903745DEA3AA
**********
   Device Identifier:         disk4s1
   Volume Name:               FX 10.15.7 Xcode - Data
   Volume UUID:               1DFA114A-0663-494A-9C49-B17A7DA5A644
   Disk / Partition UUID:     1DFA114A-0663-494A-9C49-B17A7DA5A644
   APFS Volume Group:         1DFA114A-0663-494A-9C49-B17A7DA5A644
**********
   Device Identifier:         disk4s2
   Volume Name:               FX 10.15.7 Xcode
   Volume UUID:               4499A61B-2498-4D56-B2C3-D68E6BFA232A
   Disk / Partition UUID:     4499A61B-2498-4D56-B2C3-D68E6BFA232A
   APFS Volume Group:         1DFA114A-0663-494A-9C49-B17A7DA5A644
**********
   Device Identifier:         disk4s3
   Volume Name:               Preboot
   Volume UUID:               777C34F0-08C0-4828-AD7B-51F0CA691C8F
   Disk / Partition UUID:     777C34F0-08C0-4828-AD7B-51F0CA691C8F
**********
   Device Identifier:         disk4s4
   Volume Name:               Recovery
   Volume UUID:               C761D8FE-1C5A-47E5-A10C-DCE3C5E66168
   Disk / Partition UUID:     C761D8FE-1C5A-47E5-A10C-DCE3C5E66168
**********
   Device Identifier:         disk4s5
   Volume Name:               VM
   Volume UUID:               87E0260F-58D3-4DF0-B49E-F6DB6BCC61AE
   Disk / Partition UUID:     87E0260F-58D3-4DF0-B49E-F6DB6BCC61AE
**********
   Device Identifier:         disk4s6
   Volume Name:               Big Sur DL
   Volume UUID:               EA9C60C5-7417-4E68-AAE5-E83792749DA6
   Disk / Partition UUID:     EA9C60C5-7417-4E68-AAE5-E83792749DA6
   APFS Volume Group:         D71CB355-511A-4092-8D1F-AE9731054E4B
**********
   Device Identifier:         disk4s7
   Volume Name:               Big Sur DL - Data
   Volume UUID:               D71CB355-511A-4092-8D1F-AE9731054E4B
   Disk / Partition UUID:     D71CB355-511A-4092-8D1F-AE9731054E4B
   APFS Volume Group:         D71CB355-511A-4092-8D1F-AE9731054E4B
**********
   Device Identifier:         disk4s8
   Volume Name:               Update
   Volume UUID:               BF99AEED-49FA-4EC9-A1AD-3C7A733F2D88
   Disk / Partition UUID:     BF99AEED-49FA-4EC9-A1AD-3C7A733F2D88
**********

**Comment by joevt** [comment]
Ok thanks for the list. When I finish fixing RefindPlus, you should be able to see the proper Volume Group UUIDs in the debug log.
